// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface BagSlotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.BagSlot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 slotId = 1;</code>
   * @return The slotId.
   */
  int getSlotId();

  /**
   * <code>.Message.ItemData data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.Message.ItemData data = 2;</code>
   * @return The data.
   */
  game.proto.data.ItemData getData();
  /**
   * <code>.Message.ItemData data = 2;</code>
   */
  game.proto.data.ItemDataOrBuilder getDataOrBuilder();
}
