// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerData_HeroEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerData_HeroEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerData_BagEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerData_BagEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerData_BankEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerData_BankEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationEnhance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationEnhance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Formation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Formation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationPos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationPos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationPosUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationPosUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Resource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Resource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ScenePos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ScenePos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_SceneData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_SceneData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerTask_RunTaskEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerTask_RunTaskEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_RunTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_RunTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskTarget_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskTarget_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerHero_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerHero_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerHero_EquipmentEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerHero_EquipmentEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerHero_LiLianEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerHero_LiLianEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerHero_XiuLianEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerHero_XiuLianEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeroRealm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeroRealm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Equipment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Equipment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Property_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PropertyEffect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PropertyEffect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Talent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Talent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightHeroPos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightHeroPos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightEnemyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightEnemyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeroDataRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeroDataRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_RoundRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_RoundRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Record_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_BuffRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_BuffRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Reward_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Reward_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ItemData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ItemData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_BagSlot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_BagSlot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\007Message\"\320\005\n\nPlayerData\022\013\n\003" +
      "pid\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017\n\007account\030\003 \001(\t" +
      "\022\r\n\005level\030\t \001(\005\022\017\n\007hotelCd\030\n \001(\003\022!\n\004task" +
      "\030e \001(\0132\023.Message.PlayerTask\022&\n\tsceneData" +
      "\030\311\001 \001(\0132\022.Message.SceneData\022$\n\010resource\030" +
      "\255\002 \001(\0132\021.Message.Resource\022,\n\004hero\030\221\003 \003(\013" +
      "2\035.Message.PlayerData.HeroEntry\022+\n\tfight" +
      "Info\030\365\003 \003(\0132\027.Message.FightEnemyInfo\022*\n\003" +
      "bag\030\331\004 \003(\0132\034.Message.PlayerData.BagEntry" +
      "\022\024\n\013bagCapacity\030\332\004 \001(\005\022\025\n\014bankCapacity\030\333" +
      "\004 \001(\005\022,\n\004bank\030\334\004 \003(\0132\035.Message.PlayerDat" +
      "a.BankEntry\022&\n\tformation\030\275\005 \003(\0132\022.Messag" +
      "e.Formation\022\036\n\025defaultFormationIndex\030\276\005 " +
      "\001(\005\022\034\n\023arenaFormationIndex\030\277\005 \001(\005\032@\n\tHer" +
      "oEntry\022\013\n\003key\030\001 \001(\005\022\"\n\005value\030\002 \001(\0132\023.Mes" +
      "sage.PlayerHero:\0028\001\032<\n\010BagEntry\022\013\n\003key\030\001" +
      " \001(\005\022\037\n\005value\030\002 \001(\0132\020.Message.BagSlot:\0028" +
      "\001\032=\n\tBankEntry\022\013\n\003key\030\001 \001(\005\022\037\n\005value\030\002 \001" +
      "(\0132\020.Message.BagSlot:\0028\001\"\022\n\020FormationEnh" +
      "ance\"L\n\tFormation\022\014\n\004name\030\001 \001(\t\022\"\n\003pos\030\003" +
      " \003(\0132\025.Message.FormationPos\022\r\n\005index\030\004 \001" +
      "(\005\"M\n\014FormationPos\022\r\n\005index\030\001 \001(\005\022\016\n\006her" +
      "oId\030\002 \001(\005\022\r\n\005order\030\003 \001(\005\022\017\n\007enhance\030\004 \001(" +
      "\005\"8\n\022FormationPosUpdate\022\"\n\003pos\030\002 \001(\0132\025.M" +
      "essage.FormationPos\"\200\001\n\010Resource\022\013\n\003exp\030" +
      "\n \001(\005\022\017\n\007needExp\030\013 \001(\005\022\014\n\004gold\030\014 \001(\003\022\013\n\003" +
      "lei\030\r \001(\005\022\r\n\005power\030\006 \001(\005\022\020\n\010maxPower\030\007 \001" +
      "(\005\022\032\n\022powerRecoverSecond\030\010 \001(\005\" \n\010SceneP" +
      "os\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\"7\n\tSceneData\022\n\n" +
      "\002id\030\001 \001(\005\022\036\n\003pos\030\002 \001(\0132\021.Message.ScenePo" +
      "s\"\201\001\n\nPlayerTask\0221\n\007runTask\030\003 \003(\0132 .Mess" +
      "age.PlayerTask.RunTaskEntry\032@\n\014RunTaskEn" +
      "try\022\013\n\003key\030\001 \001(\005\022\037\n\005value\030\002 \001(\0132\020.Messag" +
      "e.RunTask:\0028\001\"P\n\007RunTask\022\016\n\006taskId\030\001 \001(\005" +
      "\022\020\n\010complete\030\002 \001(\010\022#\n\006target\030\003 \003(\0132\023.Mes" +
      "sage.TaskTarget\"9\n\nTaskTarget\022\n\n\002id\030\001 \001(" +
      "\005\022\r\n\005value\030\002 \001(\005\022\020\n\010complete\030\003 \001(\010\"\223\004\n\nP" +
      "layerHero\022\n\n\002id\030\001 \001(\005\022\r\n\005level\030\002 \001(\005\022\013\n\003" +
      "exp\030\003 \001(\005\022#\n\010property\030\005 \001(\0132\021.Message.Pr" +
      "operty\022/\n\016propertyEffect\030\006 \001(\0132\027.Message" +
      ".PropertyEffect\022\037\n\006talent\030\007 \001(\0132\017.Messag" +
      "e.Talent\0225\n\tequipment\030\010 \003(\0132\".Message.Pl" +
      "ayerHero.EquipmentEntry\022/\n\006liLian\030\t \003(\0132" +
      "\037.Message.PlayerHero.LiLianEntry\0221\n\007xiuL" +
      "ian\030\n \003(\0132 .Message.PlayerHero.XiuLianEn" +
      "try\032D\n\016EquipmentEntry\022\013\n\003key\030\001 \001(\005\022!\n\005va" +
      "lue\030\002 \001(\0132\022.Message.Equipment:\0028\001\032A\n\013LiL" +
      "ianEntry\022\013\n\003key\030\001 \001(\005\022!\n\005value\030\002 \001(\0132\022.M" +
      "essage.HeroRealm:\0028\001\032B\n\014XiuLianEntry\022\013\n\003" +
      "key\030\001 \001(\005\022!\n\005value\030\002 \001(\0132\022.Message.HeroR" +
      "ealm:\0028\001\"&\n\tHeroRealm\022\n\n\002id\030\001 \001(\005\022\r\n\005lev" +
      "el\030\002 \001(\005\"K\n\tEquipment\022\n\n\002id\030\001 \001(\005\022\r\n\005lev" +
      "el\030\002 \001(\005\022#\n\010property\030\004 \001(\0132\021.Message.Pro" +
      "perty\"\265\001\n\010Property\022\n\n\002hp\030\001 \001(\005\022\016\n\006damage" +
      "\030\002 \001(\005\022\013\n\003def\030\003 \001(\005\022\r\n\005avoid\030\004 \001(\005\022\020\n\010cr" +
      "itical\030\005 \001(\005\022\026\n\016criticalDamage\030\006 \001(\005\022\r\n\005" +
      "speed\030\007 \001(\005\022\021\n\tavoidBase\030\010 \001(\005\022\024\n\014critic" +
      "alBase\030\t \001(\005\022\017\n\007defBase\030\n \001(\005\"J\n\016Propert" +
      "yEffect\022\017\n\007defRate\030\001 \001(\005\022\021\n\tavoidRate\030\002 " +
      "\001(\005\022\024\n\014criticalRate\030\003 \001(\005\"\025\n\006Talent\022\013\n\003u" +
      "se\030\002 \003(\005\"K\n\014FightHeroPos\022\016\n\006heroId\030\001 \001(\005" +
      "\022\013\n\003pos\030\002 \001(\005\022\017\n\007enhance\030\003 \001(\005\022\r\n\005order\030" +
      "\004 \001(\005\"\215\001\n\016FightEnemyInfo\022\n\n\002id\030\001 \001(\005\022\013\n\003" +
      "pos\030\002 \001(\005\022\r\n\005level\030\003 \001(\005\022#\n\010property\030\004 \001" +
      "(\0132\021.Message.Property\022 \n\004type\030\005 \001(\0162\022.Me" +
      "ssage.EnemyType\022\014\n\004name\030\006 \001(\t\"R\n\016HeroDat" +
      "aRecord\022\n\n\002id\030\001 \001(\005\022\013\n\003pos\030\002 \001(\005\022\n\n\002hp\030\003" +
      " \001(\005\022\r\n\005level\030\004 \001(\005\022\014\n\004name\030\n \001(\t\"=\n\013Rou" +
      "ndRecord\022\r\n\005round\030\001 \001(\005\022\037\n\006record\030\002 \003(\0132" +
      "\017.Message.Record\"\375\001\n\006Record\022!\n\004type\030\001 \001(" +
      "\0162\023.Message.RecordType\022\016\n\006heroId\030\002 \001(\005\022\n" +
      "\n\002id\030\003 \001(\005\022\013\n\003pos\030\004 \001(\005\022!\n\002dp\030\005 \001(\0162\025.Me" +
      "ssage.DisplayPoint\022\016\n\006target\030\013 \003(\005\022\'\n\nda" +
      "mageType\030\025 \001(\0162\023.Message.DamageType\022\r\n\005v" +
      "alue\030\026 \001(\005\022\023\n\013actionPoint\030  \001(\t\022\'\n\nbuffR" +
      "ecord\030) \001(\0132\023.Message.BuffRecord\"\270\001\n\nBuf" +
      "fRecord\022\016\n\006buffId\030\001 \001(\005\022\r\n\005round\030\002 \001(\005\022\023" +
      "\n\013remainRound\030\003 \001(\005\022\n\n\002i1\030\004 \001(\005\022\n\n\002i2\030\005 " +
      "\001(\005\022\n\n\002i3\030\006 \001(\005\022\n\n\002i4\030\007 \001(\005\022\n\n\002i5\030\010 \001(\005\022" +
      "\n\n\002f1\030\025 \001(\002\022\n\n\002f2\030\026 \001(\002\022\n\n\002f3\030\027 \001(\002\022\n\n\002f" +
      "4\030\030 \001(\002\022\n\n\002f5\030\031 \001(\002\"\201\001\n\006Reward\022!\n\004type\030d" +
      " \001(\0162\023.Message.RewardType\022\020\n\010rewardId\030\001 " +
      "\001(\005\022\r\n\005count\030\002 \001(\005\022\016\n\006heroId\030\003 \001(\005\022#\n\010pr" +
      "operty\030\n \001(\0132\021.Message.Property\"N\n\010ItemD" +
      "ata\022\016\n\006itemId\030\001 \001(\005\022\r\n\005count\030\002 \001(\005\022#\n\010pr" +
      "operty\030\003 \001(\0132\021.Message.Property\":\n\007BagSl" +
      "ot\022\016\n\006slotId\030\001 \001(\005\022\037\n\004data\030\002 \001(\0132\021.Messa" +
      "ge.ItemData*O\n\rFormationType\022\022\n\016FORMATIO" +
      "N_NONE\020\000\022\025\n\021FORMATION_DEFAULT\020\001\022\023\n\017FORMA" +
      "TION_ARENA\020\002*<\n\tEnemyType\022\014\n\010CREATURE\020\000\022" +
      "\n\n\006PLAYER\020\001\022\007\n\003NPC\020\002\022\014\n\010EXERCISE\020\003*\222\001\n\nR" +
      "ecordType\022\n\n\006ACTION\020\000\022\n\n\006ATTACK\020\001\022\021\n\rHEA" +
      "LTH_CHANGE\020\002\022\t\n\005AVOID\020\003\022\014\n\010BUFF_ADD\020\004\022\017\n" +
      "\013BUFF_REMOVE\020\005\022\017\n\013BUFF_UPDATE\020\006\022\017\n\013HERO_" +
      "ACTION\020\007\022\r\n\tSKILL_USE\020\010*E\n\nDamageType\022\021\n" +
      "\rDAMAGE_NORMAL\020\000\022\023\n\017DAMAGE_CRITICAL\020\001\022\017\n" +
      "\013DAMAGE_NONE\020\002*F\n\014DisplayPoint\022\014\n\010DP_ATT" +
      "_1\020\000\022\014\n\010DP_ATT_2\020\001\022\014\n\010DP_ATT_3\020\002\022\014\n\010DP_D" +
      "EF_1\020\003*E\n\nRewardType\022\021\n\rREWARD_NORMAL\020\000\022" +
      "\023\n\017REWARD_RESOURCE\020\001\022\017\n\013REWARD_ITEM\020\002B\025\n" +
      "\017game.proto.dataH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_PlayerData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_PlayerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerData_descriptor,
        new java.lang.String[] { "Pid", "Name", "Account", "Level", "HotelCd", "Task", "SceneData", "Resource", "Hero", "FightInfo", "Bag", "BagCapacity", "BankCapacity", "Bank", "Formation", "DefaultFormationIndex", "ArenaFormationIndex", });
    internal_static_Message_PlayerData_HeroEntry_descriptor =
      internal_static_Message_PlayerData_descriptor.getNestedTypes().get(0);
    internal_static_Message_PlayerData_HeroEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerData_HeroEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_PlayerData_BagEntry_descriptor =
      internal_static_Message_PlayerData_descriptor.getNestedTypes().get(1);
    internal_static_Message_PlayerData_BagEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerData_BagEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_PlayerData_BankEntry_descriptor =
      internal_static_Message_PlayerData_descriptor.getNestedTypes().get(2);
    internal_static_Message_PlayerData_BankEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerData_BankEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_FormationEnhance_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_FormationEnhance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationEnhance_descriptor,
        new java.lang.String[] { });
    internal_static_Message_Formation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Message_Formation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Formation_descriptor,
        new java.lang.String[] { "Name", "Pos", "Index", });
    internal_static_Message_FormationPos_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Message_FormationPos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationPos_descriptor,
        new java.lang.String[] { "Index", "HeroId", "Order", "Enhance", });
    internal_static_Message_FormationPosUpdate_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Message_FormationPosUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationPosUpdate_descriptor,
        new java.lang.String[] { "Pos", });
    internal_static_Message_Resource_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Message_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Resource_descriptor,
        new java.lang.String[] { "Exp", "NeedExp", "Gold", "Lei", "Power", "MaxPower", "PowerRecoverSecond", });
    internal_static_Message_ScenePos_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Message_ScenePos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ScenePos_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_Message_SceneData_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Message_SceneData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_SceneData_descriptor,
        new java.lang.String[] { "Id", "Pos", });
    internal_static_Message_PlayerTask_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Message_PlayerTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerTask_descriptor,
        new java.lang.String[] { "RunTask", });
    internal_static_Message_PlayerTask_RunTaskEntry_descriptor =
      internal_static_Message_PlayerTask_descriptor.getNestedTypes().get(0);
    internal_static_Message_PlayerTask_RunTaskEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerTask_RunTaskEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_RunTask_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Message_RunTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_RunTask_descriptor,
        new java.lang.String[] { "TaskId", "Complete", "Target", });
    internal_static_Message_TaskTarget_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Message_TaskTarget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskTarget_descriptor,
        new java.lang.String[] { "Id", "Value", "Complete", });
    internal_static_Message_PlayerHero_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Message_PlayerHero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerHero_descriptor,
        new java.lang.String[] { "Id", "Level", "Exp", "Property", "PropertyEffect", "Talent", "Equipment", "LiLian", "XiuLian", });
    internal_static_Message_PlayerHero_EquipmentEntry_descriptor =
      internal_static_Message_PlayerHero_descriptor.getNestedTypes().get(0);
    internal_static_Message_PlayerHero_EquipmentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerHero_EquipmentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_PlayerHero_LiLianEntry_descriptor =
      internal_static_Message_PlayerHero_descriptor.getNestedTypes().get(1);
    internal_static_Message_PlayerHero_LiLianEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerHero_LiLianEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_PlayerHero_XiuLianEntry_descriptor =
      internal_static_Message_PlayerHero_descriptor.getNestedTypes().get(2);
    internal_static_Message_PlayerHero_XiuLianEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerHero_XiuLianEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_HeroRealm_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Message_HeroRealm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeroRealm_descriptor,
        new java.lang.String[] { "Id", "Level", });
    internal_static_Message_Equipment_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Message_Equipment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Equipment_descriptor,
        new java.lang.String[] { "Id", "Level", "Property", });
    internal_static_Message_Property_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Message_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Property_descriptor,
        new java.lang.String[] { "Hp", "Damage", "Def", "Avoid", "Critical", "CriticalDamage", "Speed", "AvoidBase", "CriticalBase", "DefBase", });
    internal_static_Message_PropertyEffect_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Message_PropertyEffect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PropertyEffect_descriptor,
        new java.lang.String[] { "DefRate", "AvoidRate", "CriticalRate", });
    internal_static_Message_Talent_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Message_Talent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Talent_descriptor,
        new java.lang.String[] { "Use", });
    internal_static_Message_FightHeroPos_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Message_FightHeroPos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightHeroPos_descriptor,
        new java.lang.String[] { "HeroId", "Pos", "Enhance", "Order", });
    internal_static_Message_FightEnemyInfo_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Message_FightEnemyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightEnemyInfo_descriptor,
        new java.lang.String[] { "Id", "Pos", "Level", "Property", "Type", "Name", });
    internal_static_Message_HeroDataRecord_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Message_HeroDataRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeroDataRecord_descriptor,
        new java.lang.String[] { "Id", "Pos", "Hp", "Level", "Name", });
    internal_static_Message_RoundRecord_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Message_RoundRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_RoundRecord_descriptor,
        new java.lang.String[] { "Round", "Record", });
    internal_static_Message_Record_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Message_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Record_descriptor,
        new java.lang.String[] { "Type", "HeroId", "Id", "Pos", "Dp", "Target", "DamageType", "Value", "ActionPoint", "BuffRecord", });
    internal_static_Message_BuffRecord_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Message_BuffRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_BuffRecord_descriptor,
        new java.lang.String[] { "BuffId", "Round", "RemainRound", "I1", "I2", "I3", "I4", "I5", "F1", "F2", "F3", "F4", "F5", });
    internal_static_Message_Reward_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Message_Reward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Reward_descriptor,
        new java.lang.String[] { "Type", "RewardId", "Count", "HeroId", "Property", });
    internal_static_Message_ItemData_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Message_ItemData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ItemData_descriptor,
        new java.lang.String[] { "ItemId", "Count", "Property", });
    internal_static_Message_BagSlot_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Message_BagSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_BagSlot_descriptor,
        new java.lang.String[] { "SlotId", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
