// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

/**
 * Protobuf enum {@code Message.DisplayPoint}
 */
public enum DisplayPoint
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 出发
   * </pre>
   *
   * <code>DP_ATT_1 = 0;</code>
   */
  DP_ATT_1(0),
  /**
   * <pre>
   * 到达
   * </pre>
   *
   * <code>DP_ATT_2 = 1;</code>
   */
  DP_ATT_2(1),
  /**
   * <pre>
   * 返回
   * </pre>
   *
   * <code>DP_ATT_3 = 2;</code>
   */
  DP_ATT_3(2),
  /**
   * <code>DP_DEF_1 = 3;</code>
   */
  DP_DEF_1(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 出发
   * </pre>
   *
   * <code>DP_ATT_1 = 0;</code>
   */
  public static final int DP_ATT_1_VALUE = 0;
  /**
   * <pre>
   * 到达
   * </pre>
   *
   * <code>DP_ATT_2 = 1;</code>
   */
  public static final int DP_ATT_2_VALUE = 1;
  /**
   * <pre>
   * 返回
   * </pre>
   *
   * <code>DP_ATT_3 = 2;</code>
   */
  public static final int DP_ATT_3_VALUE = 2;
  /**
   * <code>DP_DEF_1 = 3;</code>
   */
  public static final int DP_DEF_1_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DisplayPoint valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DisplayPoint forNumber(int value) {
    switch (value) {
      case 0: return DP_ATT_1;
      case 1: return DP_ATT_2;
      case 2: return DP_ATT_3;
      case 3: return DP_DEF_1;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DisplayPoint>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DisplayPoint> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DisplayPoint>() {
          public DisplayPoint findValueByNumber(int number) {
            return DisplayPoint.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return game.proto.data.Data.getDescriptor().getEnumTypes().get(4);
  }

  private static final DisplayPoint[] VALUES = values();

  public static DisplayPoint valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DisplayPoint(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Message.DisplayPoint)
}

