// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface FightHeroHpDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FightHeroHpData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, int32&gt; data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;int32, int32&gt; data = 1;</code>
   */
  boolean containsData(
      int key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getData();
  /**
   * <code>map&lt;int32, int32&gt; data = 1;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getDataMap();
  /**
   * <code>map&lt;int32, int32&gt; data = 1;</code>
   */

  int getDataOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; data = 1;</code>
   */

  int getDataOrThrow(
      int key);
}
