// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface FightEnemyInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FightEnemyInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 pos = 2;</code>
   * @return The pos.
   */
  int getPos();

  /**
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>.Message.Property property = 4;</code>
   * @return Whether the property field is set.
   */
  boolean hasProperty();
  /**
   * <code>.Message.Property property = 4;</code>
   * @return The property.
   */
  game.proto.data.Property getProperty();
  /**
   * <code>.Message.Property property = 4;</code>
   */
  game.proto.data.PropertyOrBuilder getPropertyOrBuilder();
}
