// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface FightEnemyInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FightEnemyInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 pos = 2;</code>
   * @return The pos.
   */
  int getPos();

  /**
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>.Message.Property property = 4;</code>
   * @return Whether the property field is set.
   */
  boolean hasProperty();
  /**
   * <code>.Message.Property property = 4;</code>
   * @return The property.
   */
  game.proto.data.Property getProperty();
  /**
   * <code>.Message.Property property = 4;</code>
   */
  game.proto.data.PropertyOrBuilder getPropertyOrBuilder();

  /**
   * <code>.Message.EnemyType type = 5;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.Message.EnemyType type = 5;</code>
   * @return The type.
   */
  game.proto.data.EnemyType getType();

  /**
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
