// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface FormationUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FormationUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 formationId = 1;</code>
   * @return The formationId.
   */
  int getFormationId();

  /**
   * <code>.Message.FormationPos pos = 2;</code>
   * @return Whether the pos field is set.
   */
  boolean hasPos();
  /**
   * <code>.Message.FormationPos pos = 2;</code>
   * @return The pos.
   */
  game.proto.data.FormationPos getPos();
  /**
   * <code>.Message.FormationPos pos = 2;</code>
   */
  game.proto.data.FormationPosOrBuilder getPosOrBuilder();
}
