// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface KeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.KeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 key = 1;</code>
   * @return The key.
   */
  int getKey();

  /**
   * <code>int32 value = 2;</code>
   * @return The value.
   */
  int getValue();
}
