// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

/**
 * <pre>
 * 6英雄比赛记录
 * </pre>
 *
 * Protobuf type {@code Message.LadderReport}
 */
public final class LadderReport extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.LadderReport)
    LadderReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LadderReport.newBuilder() to construct.
  private LadderReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LadderReport() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LadderReport();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LadderReport(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            uid_ = input.readInt64();
            break;
          }
          case 18: {
            game.proto.data.FormationPos.Builder subBuilder = null;
            if (formation_ != null) {
              subBuilder = formation_.toBuilder();
            }
            formation_ = input.readMessage(game.proto.data.FormationPos.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(formation_);
              formation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return game.proto.data.Data.internal_static_Message_LadderReport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return game.proto.data.Data.internal_static_Message_LadderReport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            game.proto.data.LadderReport.class, game.proto.data.LadderReport.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  private long uid_;
  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  @java.lang.Override
  public long getUid() {
    return uid_;
  }

  public static final int FORMATION_FIELD_NUMBER = 2;
  private game.proto.data.FormationPos formation_;
  /**
   * <code>.Message.FormationPos formation = 2;</code>
   * @return Whether the formation field is set.
   */
  @java.lang.Override
  public boolean hasFormation() {
    return formation_ != null;
  }
  /**
   * <code>.Message.FormationPos formation = 2;</code>
   * @return The formation.
   */
  @java.lang.Override
  public game.proto.data.FormationPos getFormation() {
    return formation_ == null ? game.proto.data.FormationPos.getDefaultInstance() : formation_;
  }
  /**
   * <code>.Message.FormationPos formation = 2;</code>
   */
  @java.lang.Override
  public game.proto.data.FormationPosOrBuilder getFormationOrBuilder() {
    return getFormation();
  }

  public static final int NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0L) {
      output.writeInt64(1, uid_);
    }
    if (formation_ != null) {
      output.writeMessage(2, getFormation());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uid_);
    }
    if (formation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFormation());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof game.proto.data.LadderReport)) {
      return super.equals(obj);
    }
    game.proto.data.LadderReport other = (game.proto.data.LadderReport) obj;

    if (getUid()
        != other.getUid()) return false;
    if (hasFormation() != other.hasFormation()) return false;
    if (hasFormation()) {
      if (!getFormation()
          .equals(other.getFormation())) return false;
    }
    if (!getName()
        .equals(other.getName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    if (hasFormation()) {
      hash = (37 * hash) + FORMATION_FIELD_NUMBER;
      hash = (53 * hash) + getFormation().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static game.proto.data.LadderReport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.LadderReport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.LadderReport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.LadderReport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.LadderReport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.LadderReport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.LadderReport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.data.LadderReport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.data.LadderReport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static game.proto.data.LadderReport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.data.LadderReport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.data.LadderReport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(game.proto.data.LadderReport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 6英雄比赛记录
   * </pre>
   *
   * Protobuf type {@code Message.LadderReport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.LadderReport)
      game.proto.data.LadderReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.proto.data.Data.internal_static_Message_LadderReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.proto.data.Data.internal_static_Message_LadderReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.proto.data.LadderReport.class, game.proto.data.LadderReport.Builder.class);
    }

    // Construct using game.proto.data.LadderReport.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uid_ = 0L;

      if (formationBuilder_ == null) {
        formation_ = null;
      } else {
        formation_ = null;
        formationBuilder_ = null;
      }
      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return game.proto.data.Data.internal_static_Message_LadderReport_descriptor;
    }

    @java.lang.Override
    public game.proto.data.LadderReport getDefaultInstanceForType() {
      return game.proto.data.LadderReport.getDefaultInstance();
    }

    @java.lang.Override
    public game.proto.data.LadderReport build() {
      game.proto.data.LadderReport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public game.proto.data.LadderReport buildPartial() {
      game.proto.data.LadderReport result = new game.proto.data.LadderReport(this);
      result.uid_ = uid_;
      if (formationBuilder_ == null) {
        result.formation_ = formation_;
      } else {
        result.formation_ = formationBuilder_.build();
      }
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof game.proto.data.LadderReport) {
        return mergeFrom((game.proto.data.LadderReport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(game.proto.data.LadderReport other) {
      if (other == game.proto.data.LadderReport.getDefaultInstance()) return this;
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (other.hasFormation()) {
        mergeFormation(other.getFormation());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      game.proto.data.LadderReport parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (game.proto.data.LadderReport) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long uid_ ;
    /**
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }
    /**
     * <code>int64 uid = 1;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(long value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      
      uid_ = 0L;
      onChanged();
      return this;
    }

    private game.proto.data.FormationPos formation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        game.proto.data.FormationPos, game.proto.data.FormationPos.Builder, game.proto.data.FormationPosOrBuilder> formationBuilder_;
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     * @return Whether the formation field is set.
     */
    public boolean hasFormation() {
      return formationBuilder_ != null || formation_ != null;
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     * @return The formation.
     */
    public game.proto.data.FormationPos getFormation() {
      if (formationBuilder_ == null) {
        return formation_ == null ? game.proto.data.FormationPos.getDefaultInstance() : formation_;
      } else {
        return formationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     */
    public Builder setFormation(game.proto.data.FormationPos value) {
      if (formationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        formation_ = value;
        onChanged();
      } else {
        formationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     */
    public Builder setFormation(
        game.proto.data.FormationPos.Builder builderForValue) {
      if (formationBuilder_ == null) {
        formation_ = builderForValue.build();
        onChanged();
      } else {
        formationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     */
    public Builder mergeFormation(game.proto.data.FormationPos value) {
      if (formationBuilder_ == null) {
        if (formation_ != null) {
          formation_ =
            game.proto.data.FormationPos.newBuilder(formation_).mergeFrom(value).buildPartial();
        } else {
          formation_ = value;
        }
        onChanged();
      } else {
        formationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     */
    public Builder clearFormation() {
      if (formationBuilder_ == null) {
        formation_ = null;
        onChanged();
      } else {
        formation_ = null;
        formationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     */
    public game.proto.data.FormationPos.Builder getFormationBuilder() {
      
      onChanged();
      return getFormationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     */
    public game.proto.data.FormationPosOrBuilder getFormationOrBuilder() {
      if (formationBuilder_ != null) {
        return formationBuilder_.getMessageOrBuilder();
      } else {
        return formation_ == null ?
            game.proto.data.FormationPos.getDefaultInstance() : formation_;
      }
    }
    /**
     * <code>.Message.FormationPos formation = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        game.proto.data.FormationPos, game.proto.data.FormationPos.Builder, game.proto.data.FormationPosOrBuilder> 
        getFormationFieldBuilder() {
      if (formationBuilder_ == null) {
        formationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            game.proto.data.FormationPos, game.proto.data.FormationPos.Builder, game.proto.data.FormationPosOrBuilder>(
                getFormation(),
                getParentForChildren(),
                isClean());
        formation_ = null;
      }
      return formationBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.LadderReport)
  }

  // @@protoc_insertion_point(class_scope:Message.LadderReport)
  private static final game.proto.data.LadderReport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new game.proto.data.LadderReport();
  }

  public static game.proto.data.LadderReport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LadderReport>
      PARSER = new com.google.protobuf.AbstractParser<LadderReport>() {
    @java.lang.Override
    public LadderReport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LadderReport(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LadderReport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LadderReport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public game.proto.data.LadderReport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

