// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

/**
 * <pre>
 * 英雄战斗记录
 * </pre>
 *
 * Protobuf type {@code Message.LadderHeroScore}
 */
public final class LadderHeroScore extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.LadderHeroScore)
    LadderHeroScoreOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LadderHeroScore.newBuilder() to construct.
  private LadderHeroScore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LadderHeroScore() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LadderHeroScore();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LadderHeroScore(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            win1_ = input.readInt32();
            break;
          }
          case 16: {

            win2_ = input.readInt32();
            break;
          }
          case 24: {

            lose1_ = input.readInt32();
            break;
          }
          case 32: {

            lose2_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return game.proto.data.Data.internal_static_Message_LadderHeroScore_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return game.proto.data.Data.internal_static_Message_LadderHeroScore_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            game.proto.data.LadderHeroScore.class, game.proto.data.LadderHeroScore.Builder.class);
  }

  public static final int WIN1_FIELD_NUMBER = 1;
  private int win1_;
  /**
   * <pre>
   * 先手
   * </pre>
   *
   * <code>int32 win1 = 1;</code>
   * @return The win1.
   */
  @java.lang.Override
  public int getWin1() {
    return win1_;
  }

  public static final int WIN2_FIELD_NUMBER = 2;
  private int win2_;
  /**
   * <pre>
   * 后手
   * </pre>
   *
   * <code>int32 win2 = 2;</code>
   * @return The win2.
   */
  @java.lang.Override
  public int getWin2() {
    return win2_;
  }

  public static final int LOSE1_FIELD_NUMBER = 3;
  private int lose1_;
  /**
   * <pre>
   *先手
   * </pre>
   *
   * <code>int32 lose1 = 3;</code>
   * @return The lose1.
   */
  @java.lang.Override
  public int getLose1() {
    return lose1_;
  }

  public static final int LOSE2_FIELD_NUMBER = 4;
  private int lose2_;
  /**
   * <pre>
   *后手
   * </pre>
   *
   * <code>int32 lose2 = 4;</code>
   * @return The lose2.
   */
  @java.lang.Override
  public int getLose2() {
    return lose2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (win1_ != 0) {
      output.writeInt32(1, win1_);
    }
    if (win2_ != 0) {
      output.writeInt32(2, win2_);
    }
    if (lose1_ != 0) {
      output.writeInt32(3, lose1_);
    }
    if (lose2_ != 0) {
      output.writeInt32(4, lose2_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (win1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, win1_);
    }
    if (win2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, win2_);
    }
    if (lose1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lose1_);
    }
    if (lose2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, lose2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof game.proto.data.LadderHeroScore)) {
      return super.equals(obj);
    }
    game.proto.data.LadderHeroScore other = (game.proto.data.LadderHeroScore) obj;

    if (getWin1()
        != other.getWin1()) return false;
    if (getWin2()
        != other.getWin2()) return false;
    if (getLose1()
        != other.getLose1()) return false;
    if (getLose2()
        != other.getLose2()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WIN1_FIELD_NUMBER;
    hash = (53 * hash) + getWin1();
    hash = (37 * hash) + WIN2_FIELD_NUMBER;
    hash = (53 * hash) + getWin2();
    hash = (37 * hash) + LOSE1_FIELD_NUMBER;
    hash = (53 * hash) + getLose1();
    hash = (37 * hash) + LOSE2_FIELD_NUMBER;
    hash = (53 * hash) + getLose2();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static game.proto.data.LadderHeroScore parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.LadderHeroScore parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.LadderHeroScore parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.LadderHeroScore parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.LadderHeroScore parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.LadderHeroScore parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.LadderHeroScore parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.data.LadderHeroScore parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.data.LadderHeroScore parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static game.proto.data.LadderHeroScore parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.data.LadderHeroScore parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.data.LadderHeroScore parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(game.proto.data.LadderHeroScore prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 英雄战斗记录
   * </pre>
   *
   * Protobuf type {@code Message.LadderHeroScore}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.LadderHeroScore)
      game.proto.data.LadderHeroScoreOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.proto.data.Data.internal_static_Message_LadderHeroScore_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.proto.data.Data.internal_static_Message_LadderHeroScore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.proto.data.LadderHeroScore.class, game.proto.data.LadderHeroScore.Builder.class);
    }

    // Construct using game.proto.data.LadderHeroScore.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      win1_ = 0;

      win2_ = 0;

      lose1_ = 0;

      lose2_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return game.proto.data.Data.internal_static_Message_LadderHeroScore_descriptor;
    }

    @java.lang.Override
    public game.proto.data.LadderHeroScore getDefaultInstanceForType() {
      return game.proto.data.LadderHeroScore.getDefaultInstance();
    }

    @java.lang.Override
    public game.proto.data.LadderHeroScore build() {
      game.proto.data.LadderHeroScore result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public game.proto.data.LadderHeroScore buildPartial() {
      game.proto.data.LadderHeroScore result = new game.proto.data.LadderHeroScore(this);
      result.win1_ = win1_;
      result.win2_ = win2_;
      result.lose1_ = lose1_;
      result.lose2_ = lose2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof game.proto.data.LadderHeroScore) {
        return mergeFrom((game.proto.data.LadderHeroScore)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(game.proto.data.LadderHeroScore other) {
      if (other == game.proto.data.LadderHeroScore.getDefaultInstance()) return this;
      if (other.getWin1() != 0) {
        setWin1(other.getWin1());
      }
      if (other.getWin2() != 0) {
        setWin2(other.getWin2());
      }
      if (other.getLose1() != 0) {
        setLose1(other.getLose1());
      }
      if (other.getLose2() != 0) {
        setLose2(other.getLose2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      game.proto.data.LadderHeroScore parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (game.proto.data.LadderHeroScore) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int win1_ ;
    /**
     * <pre>
     * 先手
     * </pre>
     *
     * <code>int32 win1 = 1;</code>
     * @return The win1.
     */
    @java.lang.Override
    public int getWin1() {
      return win1_;
    }
    /**
     * <pre>
     * 先手
     * </pre>
     *
     * <code>int32 win1 = 1;</code>
     * @param value The win1 to set.
     * @return This builder for chaining.
     */
    public Builder setWin1(int value) {
      
      win1_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 先手
     * </pre>
     *
     * <code>int32 win1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWin1() {
      
      win1_ = 0;
      onChanged();
      return this;
    }

    private int win2_ ;
    /**
     * <pre>
     * 后手
     * </pre>
     *
     * <code>int32 win2 = 2;</code>
     * @return The win2.
     */
    @java.lang.Override
    public int getWin2() {
      return win2_;
    }
    /**
     * <pre>
     * 后手
     * </pre>
     *
     * <code>int32 win2 = 2;</code>
     * @param value The win2 to set.
     * @return This builder for chaining.
     */
    public Builder setWin2(int value) {
      
      win2_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 后手
     * </pre>
     *
     * <code>int32 win2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWin2() {
      
      win2_ = 0;
      onChanged();
      return this;
    }

    private int lose1_ ;
    /**
     * <pre>
     *先手
     * </pre>
     *
     * <code>int32 lose1 = 3;</code>
     * @return The lose1.
     */
    @java.lang.Override
    public int getLose1() {
      return lose1_;
    }
    /**
     * <pre>
     *先手
     * </pre>
     *
     * <code>int32 lose1 = 3;</code>
     * @param value The lose1 to set.
     * @return This builder for chaining.
     */
    public Builder setLose1(int value) {
      
      lose1_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *先手
     * </pre>
     *
     * <code>int32 lose1 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLose1() {
      
      lose1_ = 0;
      onChanged();
      return this;
    }

    private int lose2_ ;
    /**
     * <pre>
     *后手
     * </pre>
     *
     * <code>int32 lose2 = 4;</code>
     * @return The lose2.
     */
    @java.lang.Override
    public int getLose2() {
      return lose2_;
    }
    /**
     * <pre>
     *后手
     * </pre>
     *
     * <code>int32 lose2 = 4;</code>
     * @param value The lose2 to set.
     * @return This builder for chaining.
     */
    public Builder setLose2(int value) {
      
      lose2_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *后手
     * </pre>
     *
     * <code>int32 lose2 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLose2() {
      
      lose2_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.LadderHeroScore)
  }

  // @@protoc_insertion_point(class_scope:Message.LadderHeroScore)
  private static final game.proto.data.LadderHeroScore DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new game.proto.data.LadderHeroScore();
  }

  public static game.proto.data.LadderHeroScore getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LadderHeroScore>
      PARSER = new com.google.protobuf.AbstractParser<LadderHeroScore>() {
    @java.lang.Override
    public LadderHeroScore parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LadderHeroScore(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LadderHeroScore> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LadderHeroScore> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public game.proto.data.LadderHeroScore getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

