// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface PlayerHeroOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.PlayerHero)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>repeated .Message.Equipment equipment = 4;</code>
   */
  java.util.List<game.proto.data.Equipment> 
      getEquipmentList();
  /**
   * <code>repeated .Message.Equipment equipment = 4;</code>
   */
  game.proto.data.Equipment getEquipment(int index);
  /**
   * <code>repeated .Message.Equipment equipment = 4;</code>
   */
  int getEquipmentCount();
  /**
   * <code>repeated .Message.Equipment equipment = 4;</code>
   */
  java.util.List<? extends game.proto.data.EquipmentOrBuilder> 
      getEquipmentOrBuilderList();
  /**
   * <code>repeated .Message.Equipment equipment = 4;</code>
   */
  game.proto.data.EquipmentOrBuilder getEquipmentOrBuilder(
      int index);

  /**
   * <code>.Message.Property property = 5;</code>
   * @return Whether the property field is set.
   */
  boolean hasProperty();
  /**
   * <code>.Message.Property property = 5;</code>
   * @return The property.
   */
  game.proto.data.Property getProperty();
  /**
   * <code>.Message.Property property = 5;</code>
   */
  game.proto.data.PropertyOrBuilder getPropertyOrBuilder();

  /**
   * <code>.Message.PropertyEffect propertyEffect = 6;</code>
   * @return Whether the propertyEffect field is set.
   */
  boolean hasPropertyEffect();
  /**
   * <code>.Message.PropertyEffect propertyEffect = 6;</code>
   * @return The propertyEffect.
   */
  game.proto.data.PropertyEffect getPropertyEffect();
  /**
   * <code>.Message.PropertyEffect propertyEffect = 6;</code>
   */
  game.proto.data.PropertyEffectOrBuilder getPropertyEffectOrBuilder();

  /**
   * <code>.Message.Talent talent = 7;</code>
   * @return Whether the talent field is set.
   */
  boolean hasTalent();
  /**
   * <code>.Message.Talent talent = 7;</code>
   * @return The talent.
   */
  game.proto.data.Talent getTalent();
  /**
   * <code>.Message.Talent talent = 7;</code>
   */
  game.proto.data.TalentOrBuilder getTalentOrBuilder();
}
