// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface PlayerHeroOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.PlayerHero)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 level = 2;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int32 exp = 3;</code>
   * @return The exp.
   */
  int getExp();

  /**
   * <code>.Message.Property property = 5;</code>
   * @return Whether the property field is set.
   */
  boolean hasProperty();
  /**
   * <code>.Message.Property property = 5;</code>
   * @return The property.
   */
  game.proto.data.Property getProperty();
  /**
   * <code>.Message.Property property = 5;</code>
   */
  game.proto.data.PropertyOrBuilder getPropertyOrBuilder();

  /**
   * <code>.Message.PropertyEffect propertyEffect = 6;</code>
   * @return Whether the propertyEffect field is set.
   */
  boolean hasPropertyEffect();
  /**
   * <code>.Message.PropertyEffect propertyEffect = 6;</code>
   * @return The propertyEffect.
   */
  game.proto.data.PropertyEffect getPropertyEffect();
  /**
   * <code>.Message.PropertyEffect propertyEffect = 6;</code>
   */
  game.proto.data.PropertyEffectOrBuilder getPropertyEffectOrBuilder();

  /**
   * <code>.Message.Talent talent = 7;</code>
   * @return Whether the talent field is set.
   */
  boolean hasTalent();
  /**
   * <code>.Message.Talent talent = 7;</code>
   * @return The talent.
   */
  game.proto.data.Talent getTalent();
  /**
   * <code>.Message.Talent talent = 7;</code>
   */
  game.proto.data.TalentOrBuilder getTalentOrBuilder();

  /**
   * <code>map&lt;int32, .Message.Equipment&gt; equipment = 8;</code>
   */
  int getEquipmentCount();
  /**
   * <code>map&lt;int32, .Message.Equipment&gt; equipment = 8;</code>
   */
  boolean containsEquipment(
      int key);
  /**
   * Use {@link #getEquipmentMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, game.proto.data.Equipment>
  getEquipment();
  /**
   * <code>map&lt;int32, .Message.Equipment&gt; equipment = 8;</code>
   */
  java.util.Map<java.lang.Integer, game.proto.data.Equipment>
  getEquipmentMap();
  /**
   * <code>map&lt;int32, .Message.Equipment&gt; equipment = 8;</code>
   */

  game.proto.data.Equipment getEquipmentOrDefault(
      int key,
      game.proto.data.Equipment defaultValue);
  /**
   * <code>map&lt;int32, .Message.Equipment&gt; equipment = 8;</code>
   */

  game.proto.data.Equipment getEquipmentOrThrow(
      int key);

  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; liLian = 9;</code>
   */
  int getLiLianCount();
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; liLian = 9;</code>
   */
  boolean containsLiLian(
      int key);
  /**
   * Use {@link #getLiLianMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, game.proto.data.HeroRealm>
  getLiLian();
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; liLian = 9;</code>
   */
  java.util.Map<java.lang.Integer, game.proto.data.HeroRealm>
  getLiLianMap();
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; liLian = 9;</code>
   */

  game.proto.data.HeroRealm getLiLianOrDefault(
      int key,
      game.proto.data.HeroRealm defaultValue);
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; liLian = 9;</code>
   */

  game.proto.data.HeroRealm getLiLianOrThrow(
      int key);

  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; xiuLian = 10;</code>
   */
  int getXiuLianCount();
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; xiuLian = 10;</code>
   */
  boolean containsXiuLian(
      int key);
  /**
   * Use {@link #getXiuLianMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, game.proto.data.HeroRealm>
  getXiuLian();
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; xiuLian = 10;</code>
   */
  java.util.Map<java.lang.Integer, game.proto.data.HeroRealm>
  getXiuLianMap();
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; xiuLian = 10;</code>
   */

  game.proto.data.HeroRealm getXiuLianOrDefault(
      int key,
      game.proto.data.HeroRealm defaultValue);
  /**
   * <code>map&lt;int32, .Message.HeroRealm&gt; xiuLian = 10;</code>
   */

  game.proto.data.HeroRealm getXiuLianOrThrow(
      int key);
}
