// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

/**
 * <pre>
 * 属性效果 v/100
 * </pre>
 *
 * Protobuf type {@code Message.PropertyEffect}
 */
public final class PropertyEffect extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.PropertyEffect)
    PropertyEffectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PropertyEffect.newBuilder() to construct.
  private PropertyEffect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PropertyEffect() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PropertyEffect();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PropertyEffect(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            defRate_ = input.readInt32();
            break;
          }
          case 16: {

            avoidRate_ = input.readInt32();
            break;
          }
          case 24: {

            criticalRate_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return game.proto.data.Data.internal_static_Message_PropertyEffect_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return game.proto.data.Data.internal_static_Message_PropertyEffect_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            game.proto.data.PropertyEffect.class, game.proto.data.PropertyEffect.Builder.class);
  }

  public static final int DEFRATE_FIELD_NUMBER = 1;
  private int defRate_;
  /**
   * <pre>
   *减伤(百分比)
   * </pre>
   *
   * <code>int32 defRate = 1;</code>
   * @return The defRate.
   */
  @java.lang.Override
  public int getDefRate() {
    return defRate_;
  }

  public static final int AVOIDRATE_FIELD_NUMBER = 2;
  private int avoidRate_;
  /**
   * <pre>
   *暴击概率
   * </pre>
   *
   * <code>int32 avoidRate = 2;</code>
   * @return The avoidRate.
   */
  @java.lang.Override
  public int getAvoidRate() {
    return avoidRate_;
  }

  public static final int CRITICALRATE_FIELD_NUMBER = 3;
  private int criticalRate_;
  /**
   * <pre>
   *闪避概率
   * </pre>
   *
   * <code>int32 criticalRate = 3;</code>
   * @return The criticalRate.
   */
  @java.lang.Override
  public int getCriticalRate() {
    return criticalRate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (defRate_ != 0) {
      output.writeInt32(1, defRate_);
    }
    if (avoidRate_ != 0) {
      output.writeInt32(2, avoidRate_);
    }
    if (criticalRate_ != 0) {
      output.writeInt32(3, criticalRate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (defRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, defRate_);
    }
    if (avoidRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, avoidRate_);
    }
    if (criticalRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, criticalRate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof game.proto.data.PropertyEffect)) {
      return super.equals(obj);
    }
    game.proto.data.PropertyEffect other = (game.proto.data.PropertyEffect) obj;

    if (getDefRate()
        != other.getDefRate()) return false;
    if (getAvoidRate()
        != other.getAvoidRate()) return false;
    if (getCriticalRate()
        != other.getCriticalRate()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEFRATE_FIELD_NUMBER;
    hash = (53 * hash) + getDefRate();
    hash = (37 * hash) + AVOIDRATE_FIELD_NUMBER;
    hash = (53 * hash) + getAvoidRate();
    hash = (37 * hash) + CRITICALRATE_FIELD_NUMBER;
    hash = (53 * hash) + getCriticalRate();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static game.proto.data.PropertyEffect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.PropertyEffect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.PropertyEffect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.PropertyEffect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.PropertyEffect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.data.PropertyEffect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.data.PropertyEffect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.data.PropertyEffect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.data.PropertyEffect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static game.proto.data.PropertyEffect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.data.PropertyEffect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.data.PropertyEffect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(game.proto.data.PropertyEffect prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 属性效果 v/100
   * </pre>
   *
   * Protobuf type {@code Message.PropertyEffect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.PropertyEffect)
      game.proto.data.PropertyEffectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.proto.data.Data.internal_static_Message_PropertyEffect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.proto.data.Data.internal_static_Message_PropertyEffect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.proto.data.PropertyEffect.class, game.proto.data.PropertyEffect.Builder.class);
    }

    // Construct using game.proto.data.PropertyEffect.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      defRate_ = 0;

      avoidRate_ = 0;

      criticalRate_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return game.proto.data.Data.internal_static_Message_PropertyEffect_descriptor;
    }

    @java.lang.Override
    public game.proto.data.PropertyEffect getDefaultInstanceForType() {
      return game.proto.data.PropertyEffect.getDefaultInstance();
    }

    @java.lang.Override
    public game.proto.data.PropertyEffect build() {
      game.proto.data.PropertyEffect result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public game.proto.data.PropertyEffect buildPartial() {
      game.proto.data.PropertyEffect result = new game.proto.data.PropertyEffect(this);
      result.defRate_ = defRate_;
      result.avoidRate_ = avoidRate_;
      result.criticalRate_ = criticalRate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof game.proto.data.PropertyEffect) {
        return mergeFrom((game.proto.data.PropertyEffect)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(game.proto.data.PropertyEffect other) {
      if (other == game.proto.data.PropertyEffect.getDefaultInstance()) return this;
      if (other.getDefRate() != 0) {
        setDefRate(other.getDefRate());
      }
      if (other.getAvoidRate() != 0) {
        setAvoidRate(other.getAvoidRate());
      }
      if (other.getCriticalRate() != 0) {
        setCriticalRate(other.getCriticalRate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      game.proto.data.PropertyEffect parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (game.proto.data.PropertyEffect) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int defRate_ ;
    /**
     * <pre>
     *减伤(百分比)
     * </pre>
     *
     * <code>int32 defRate = 1;</code>
     * @return The defRate.
     */
    @java.lang.Override
    public int getDefRate() {
      return defRate_;
    }
    /**
     * <pre>
     *减伤(百分比)
     * </pre>
     *
     * <code>int32 defRate = 1;</code>
     * @param value The defRate to set.
     * @return This builder for chaining.
     */
    public Builder setDefRate(int value) {
      
      defRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *减伤(百分比)
     * </pre>
     *
     * <code>int32 defRate = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefRate() {
      
      defRate_ = 0;
      onChanged();
      return this;
    }

    private int avoidRate_ ;
    /**
     * <pre>
     *暴击概率
     * </pre>
     *
     * <code>int32 avoidRate = 2;</code>
     * @return The avoidRate.
     */
    @java.lang.Override
    public int getAvoidRate() {
      return avoidRate_;
    }
    /**
     * <pre>
     *暴击概率
     * </pre>
     *
     * <code>int32 avoidRate = 2;</code>
     * @param value The avoidRate to set.
     * @return This builder for chaining.
     */
    public Builder setAvoidRate(int value) {
      
      avoidRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *暴击概率
     * </pre>
     *
     * <code>int32 avoidRate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvoidRate() {
      
      avoidRate_ = 0;
      onChanged();
      return this;
    }

    private int criticalRate_ ;
    /**
     * <pre>
     *闪避概率
     * </pre>
     *
     * <code>int32 criticalRate = 3;</code>
     * @return The criticalRate.
     */
    @java.lang.Override
    public int getCriticalRate() {
      return criticalRate_;
    }
    /**
     * <pre>
     *闪避概率
     * </pre>
     *
     * <code>int32 criticalRate = 3;</code>
     * @param value The criticalRate to set.
     * @return This builder for chaining.
     */
    public Builder setCriticalRate(int value) {
      
      criticalRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *闪避概率
     * </pre>
     *
     * <code>int32 criticalRate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCriticalRate() {
      
      criticalRate_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.PropertyEffect)
  }

  // @@protoc_insertion_point(class_scope:Message.PropertyEffect)
  private static final game.proto.data.PropertyEffect DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new game.proto.data.PropertyEffect();
  }

  public static game.proto.data.PropertyEffect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PropertyEffect>
      PARSER = new com.google.protobuf.AbstractParser<PropertyEffect>() {
    @java.lang.Override
    public PropertyEffect parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PropertyEffect(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PropertyEffect> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PropertyEffect> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public game.proto.data.PropertyEffect getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

