// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Message.RecordType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.Message.RecordType type = 1;</code>
   * @return The type.
   */
  game.proto.data.RecordType getType();

  /**
   * <code>int32 heroId = 2;</code>
   * @return The heroId.
   */
  int getHeroId();

  /**
   * <code>int32 id = 3;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 pos = 4;</code>
   * @return The pos.
   */
  int getPos();

  /**
   * <code>repeated int32 target = 11;</code>
   * @return A list containing the target.
   */
  java.util.List<java.lang.Integer> getTargetList();
  /**
   * <code>repeated int32 target = 11;</code>
   * @return The count of target.
   */
  int getTargetCount();
  /**
   * <code>repeated int32 target = 11;</code>
   * @param index The index of the element to return.
   * @return The target at the given index.
   */
  int getTarget(int index);

  /**
   * <code>.Message.DamageType damageType = 21;</code>
   * @return The enum numeric value on the wire for damageType.
   */
  int getDamageTypeValue();
  /**
   * <code>.Message.DamageType damageType = 21;</code>
   * @return The damageType.
   */
  game.proto.data.DamageType getDamageType();

  /**
   * <code>int32 value = 22;</code>
   * @return The value.
   */
  int getValue();

  /**
   * <code>string actionPoint = 32;</code>
   * @return The actionPoint.
   */
  java.lang.String getActionPoint();
  /**
   * <code>string actionPoint = 32;</code>
   * @return The bytes for actionPoint.
   */
  com.google.protobuf.ByteString
      getActionPointBytes();

  /**
   * <code>.Message.BuffRecord buffRecord = 41;</code>
   * @return Whether the buffRecord field is set.
   */
  boolean hasBuffRecord();
  /**
   * <code>.Message.BuffRecord buffRecord = 41;</code>
   * @return The buffRecord.
   */
  game.proto.data.BuffRecord getBuffRecord();
  /**
   * <code>.Message.BuffRecord buffRecord = 41;</code>
   */
  game.proto.data.BuffRecordOrBuilder getBuffRecordOrBuilder();
}
