// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface RoundRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.RoundRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 round = 1;</code>
   * @return The round.
   */
  int getRound();

  /**
   * <code>repeated .Message.Record record = 2;</code>
   */
  java.util.List<game.proto.data.Record> 
      getRecordList();
  /**
   * <code>repeated .Message.Record record = 2;</code>
   */
  game.proto.data.Record getRecord(int index);
  /**
   * <code>repeated .Message.Record record = 2;</code>
   */
  int getRecordCount();
  /**
   * <code>repeated .Message.Record record = 2;</code>
   */
  java.util.List<? extends game.proto.data.RecordOrBuilder> 
      getRecordOrBuilderList();
  /**
   * <code>repeated .Message.Record record = 2;</code>
   */
  game.proto.data.RecordOrBuilder getRecordOrBuilder(
      int index);
}
