// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package game.proto.data;

public interface RunTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.RunTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 taskId = 1;</code>
   * @return The taskId.
   */
  int getTaskId();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>repeated .Message.TaskTarget target = 3;</code>
   */
  java.util.List<game.proto.data.TaskTarget> 
      getTargetList();
  /**
   * <code>repeated .Message.TaskTarget target = 3;</code>
   */
  game.proto.data.TaskTarget getTarget(int index);
  /**
   * <code>repeated .Message.TaskTarget target = 3;</code>
   */
  int getTargetCount();
  /**
   * <code>repeated .Message.TaskTarget target = 3;</code>
   */
  java.util.List<? extends game.proto.data.TaskTargetOrBuilder> 
      getTargetOrBuilderList();
  /**
   * <code>repeated .Message.TaskTarget target = 3;</code>
   */
  game.proto.data.TaskTargetOrBuilder getTargetOrBuilder(
      int index);
}
