// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface EnterSceneReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.EnterSceneReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Message.SceneData data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.Message.SceneData data = 1;</code>
   * @return The data.
   */
  game.proto.data.SceneData getData();
  /**
   * <code>.Message.SceneData data = 1;</code>
   */
  game.proto.data.SceneDataOrBuilder getDataOrBuilder();
}
