// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface ExpChangePushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.ExpChangePush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heroId = 1;</code>
   * @return The heroId.
   */
  int getHeroId();

  /**
   * <code>int32 addExp = 2;</code>
   * @return The addExp.
   */
  int getAddExp();

  /**
   * <code>int32 curExp = 3;</code>
   * @return The curExp.
   */
  int getCurExp();
}
