// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface FightHmEndResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FightHmEndRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Message.RoundRecord round = 1;</code>
   * @return Whether the round field is set.
   */
  boolean hasRound();
  /**
   * <code>.Message.RoundRecord round = 1;</code>
   * @return The round.
   */
  game.proto.data.RoundRecord getRound();
  /**
   * <code>.Message.RoundRecord round = 1;</code>
   */
  game.proto.data.RoundRecordOrBuilder getRoundOrBuilder();

  /**
   * <pre>
   * 是否胜利
   * </pre>
   *
   * <code>bool win = 4;</code>
   * @return The win.
   */
  boolean getWin();

  /**
   * <pre>
   * 奖励
   * </pre>
   *
   * <code>repeated .Message.Reward reward = 5;</code>
   */
  java.util.List<game.proto.data.Reward> 
      getRewardList();
  /**
   * <pre>
   * 奖励
   * </pre>
   *
   * <code>repeated .Message.Reward reward = 5;</code>
   */
  game.proto.data.Reward getReward(int index);
  /**
   * <pre>
   * 奖励
   * </pre>
   *
   * <code>repeated .Message.Reward reward = 5;</code>
   */
  int getRewardCount();
  /**
   * <pre>
   * 奖励
   * </pre>
   *
   * <code>repeated .Message.Reward reward = 5;</code>
   */
  java.util.List<? extends game.proto.data.RewardOrBuilder> 
      getRewardOrBuilderList();
  /**
   * <pre>
   * 奖励
   * </pre>
   *
   * <code>repeated .Message.Reward reward = 5;</code>
   */
  game.proto.data.RewardOrBuilder getRewardOrBuilder(
      int index);
}
