// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

/**
 * <pre>
 * 钓鱼-成功发送奖励
 * </pre>
 *
 * Protobuf type {@code Message.FishPush}
 */
public final class FishPush extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.FishPush)
    FishPushOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FishPush.newBuilder() to construct.
  private FishPush(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FishPush() {
    reward_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FishPush();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FishPush(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reward_ = new java.util.ArrayList<game.proto.data.Reward>();
              mutable_bitField0_ |= 0x00000001;
            }
            reward_.add(
                input.readMessage(game.proto.data.Reward.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        reward_ = java.util.Collections.unmodifiableList(reward_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return game.proto.MessageOuterClass.internal_static_Message_FishPush_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return game.proto.MessageOuterClass.internal_static_Message_FishPush_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            game.proto.FishPush.class, game.proto.FishPush.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int REWARD_FIELD_NUMBER = 2;
  private java.util.List<game.proto.data.Reward> reward_;
  /**
   * <code>repeated .Message.Reward reward = 2;</code>
   */
  @java.lang.Override
  public java.util.List<game.proto.data.Reward> getRewardList() {
    return reward_;
  }
  /**
   * <code>repeated .Message.Reward reward = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends game.proto.data.RewardOrBuilder> 
      getRewardOrBuilderList() {
    return reward_;
  }
  /**
   * <code>repeated .Message.Reward reward = 2;</code>
   */
  @java.lang.Override
  public int getRewardCount() {
    return reward_.size();
  }
  /**
   * <code>repeated .Message.Reward reward = 2;</code>
   */
  @java.lang.Override
  public game.proto.data.Reward getReward(int index) {
    return reward_.get(index);
  }
  /**
   * <code>repeated .Message.Reward reward = 2;</code>
   */
  @java.lang.Override
  public game.proto.data.RewardOrBuilder getRewardOrBuilder(
      int index) {
    return reward_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    for (int i = 0; i < reward_.size(); i++) {
      output.writeMessage(2, reward_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    for (int i = 0; i < reward_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, reward_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof game.proto.FishPush)) {
      return super.equals(obj);
    }
    game.proto.FishPush other = (game.proto.FishPush) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getRewardList()
        .equals(other.getRewardList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (getRewardCount() > 0) {
      hash = (37 * hash) + REWARD_FIELD_NUMBER;
      hash = (53 * hash) + getRewardList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static game.proto.FishPush parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.FishPush parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.FishPush parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.FishPush parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.FishPush parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.FishPush parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.FishPush parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.FishPush parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.FishPush parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static game.proto.FishPush parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.FishPush parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.FishPush parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(game.proto.FishPush prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 钓鱼-成功发送奖励
   * </pre>
   *
   * Protobuf type {@code Message.FishPush}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.FishPush)
      game.proto.FishPushOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.proto.MessageOuterClass.internal_static_Message_FishPush_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.proto.MessageOuterClass.internal_static_Message_FishPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.proto.FishPush.class, game.proto.FishPush.Builder.class);
    }

    // Construct using game.proto.FishPush.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRewardFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      success_ = false;

      if (rewardBuilder_ == null) {
        reward_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rewardBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return game.proto.MessageOuterClass.internal_static_Message_FishPush_descriptor;
    }

    @java.lang.Override
    public game.proto.FishPush getDefaultInstanceForType() {
      return game.proto.FishPush.getDefaultInstance();
    }

    @java.lang.Override
    public game.proto.FishPush build() {
      game.proto.FishPush result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public game.proto.FishPush buildPartial() {
      game.proto.FishPush result = new game.proto.FishPush(this);
      int from_bitField0_ = bitField0_;
      result.success_ = success_;
      if (rewardBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          reward_ = java.util.Collections.unmodifiableList(reward_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.reward_ = reward_;
      } else {
        result.reward_ = rewardBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof game.proto.FishPush) {
        return mergeFrom((game.proto.FishPush)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(game.proto.FishPush other) {
      if (other == game.proto.FishPush.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (rewardBuilder_ == null) {
        if (!other.reward_.isEmpty()) {
          if (reward_.isEmpty()) {
            reward_ = other.reward_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRewardIsMutable();
            reward_.addAll(other.reward_);
          }
          onChanged();
        }
      } else {
        if (!other.reward_.isEmpty()) {
          if (rewardBuilder_.isEmpty()) {
            rewardBuilder_.dispose();
            rewardBuilder_ = null;
            reward_ = other.reward_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rewardBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRewardFieldBuilder() : null;
          } else {
            rewardBuilder_.addAllMessages(other.reward_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      game.proto.FishPush parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (game.proto.FishPush) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private java.util.List<game.proto.data.Reward> reward_ =
      java.util.Collections.emptyList();
    private void ensureRewardIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reward_ = new java.util.ArrayList<game.proto.data.Reward>(reward_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        game.proto.data.Reward, game.proto.data.Reward.Builder, game.proto.data.RewardOrBuilder> rewardBuilder_;

    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public java.util.List<game.proto.data.Reward> getRewardList() {
      if (rewardBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reward_);
      } else {
        return rewardBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public int getRewardCount() {
      if (rewardBuilder_ == null) {
        return reward_.size();
      } else {
        return rewardBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public game.proto.data.Reward getReward(int index) {
      if (rewardBuilder_ == null) {
        return reward_.get(index);
      } else {
        return rewardBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder setReward(
        int index, game.proto.data.Reward value) {
      if (rewardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardIsMutable();
        reward_.set(index, value);
        onChanged();
      } else {
        rewardBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder setReward(
        int index, game.proto.data.Reward.Builder builderForValue) {
      if (rewardBuilder_ == null) {
        ensureRewardIsMutable();
        reward_.set(index, builderForValue.build());
        onChanged();
      } else {
        rewardBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder addReward(game.proto.data.Reward value) {
      if (rewardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardIsMutable();
        reward_.add(value);
        onChanged();
      } else {
        rewardBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder addReward(
        int index, game.proto.data.Reward value) {
      if (rewardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardIsMutable();
        reward_.add(index, value);
        onChanged();
      } else {
        rewardBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder addReward(
        game.proto.data.Reward.Builder builderForValue) {
      if (rewardBuilder_ == null) {
        ensureRewardIsMutable();
        reward_.add(builderForValue.build());
        onChanged();
      } else {
        rewardBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder addReward(
        int index, game.proto.data.Reward.Builder builderForValue) {
      if (rewardBuilder_ == null) {
        ensureRewardIsMutable();
        reward_.add(index, builderForValue.build());
        onChanged();
      } else {
        rewardBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder addAllReward(
        java.lang.Iterable<? extends game.proto.data.Reward> values) {
      if (rewardBuilder_ == null) {
        ensureRewardIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reward_);
        onChanged();
      } else {
        rewardBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder clearReward() {
      if (rewardBuilder_ == null) {
        reward_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rewardBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public Builder removeReward(int index) {
      if (rewardBuilder_ == null) {
        ensureRewardIsMutable();
        reward_.remove(index);
        onChanged();
      } else {
        rewardBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public game.proto.data.Reward.Builder getRewardBuilder(
        int index) {
      return getRewardFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public game.proto.data.RewardOrBuilder getRewardOrBuilder(
        int index) {
      if (rewardBuilder_ == null) {
        return reward_.get(index);  } else {
        return rewardBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public java.util.List<? extends game.proto.data.RewardOrBuilder> 
         getRewardOrBuilderList() {
      if (rewardBuilder_ != null) {
        return rewardBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reward_);
      }
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public game.proto.data.Reward.Builder addRewardBuilder() {
      return getRewardFieldBuilder().addBuilder(
          game.proto.data.Reward.getDefaultInstance());
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public game.proto.data.Reward.Builder addRewardBuilder(
        int index) {
      return getRewardFieldBuilder().addBuilder(
          index, game.proto.data.Reward.getDefaultInstance());
    }
    /**
     * <code>repeated .Message.Reward reward = 2;</code>
     */
    public java.util.List<game.proto.data.Reward.Builder> 
         getRewardBuilderList() {
      return getRewardFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        game.proto.data.Reward, game.proto.data.Reward.Builder, game.proto.data.RewardOrBuilder> 
        getRewardFieldBuilder() {
      if (rewardBuilder_ == null) {
        rewardBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            game.proto.data.Reward, game.proto.data.Reward.Builder, game.proto.data.RewardOrBuilder>(
                reward_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        reward_ = null;
      }
      return rewardBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.FishPush)
  }

  // @@protoc_insertion_point(class_scope:Message.FishPush)
  private static final game.proto.FishPush DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new game.proto.FishPush();
  }

  public static game.proto.FishPush getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FishPush>
      PARSER = new com.google.protobuf.AbstractParser<FishPush>() {
    @java.lang.Override
    public FishPush parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FishPush(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FishPush> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FishPush> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public game.proto.FishPush getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

