// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface FormationListReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FormationListReq)
    com.google.protobuf.MessageOrBuilder {
}
