// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface FormationDeleteReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FormationDeleteReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  int getIndex();
}
