// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface HeartbeatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.HeartbeatReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();
}
