// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

/**
 * <pre>
 * 4003 英雄变化
 * </pre>
 *
 * Protobuf type {@code Message.HeroChangePush}
 */
public final class HeroChangePush extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.HeroChangePush)
    HeroChangePushOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeroChangePush.newBuilder() to construct.
  private HeroChangePush(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeroChangePush() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeroChangePush();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeroChangePush(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            game.proto.data.PlayerHero.Builder subBuilder = null;
            if (hero_ != null) {
              subBuilder = hero_.toBuilder();
            }
            hero_ = input.readMessage(game.proto.data.PlayerHero.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hero_);
              hero_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return game.proto.MessageOuterClass.internal_static_Message_HeroChangePush_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return game.proto.MessageOuterClass.internal_static_Message_HeroChangePush_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            game.proto.HeroChangePush.class, game.proto.HeroChangePush.Builder.class);
  }

  public static final int HERO_FIELD_NUMBER = 1;
  private game.proto.data.PlayerHero hero_;
  /**
   * <code>.Message.PlayerHero hero = 1;</code>
   * @return Whether the hero field is set.
   */
  @java.lang.Override
  public boolean hasHero() {
    return hero_ != null;
  }
  /**
   * <code>.Message.PlayerHero hero = 1;</code>
   * @return The hero.
   */
  @java.lang.Override
  public game.proto.data.PlayerHero getHero() {
    return hero_ == null ? game.proto.data.PlayerHero.getDefaultInstance() : hero_;
  }
  /**
   * <code>.Message.PlayerHero hero = 1;</code>
   */
  @java.lang.Override
  public game.proto.data.PlayerHeroOrBuilder getHeroOrBuilder() {
    return getHero();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hero_ != null) {
      output.writeMessage(1, getHero());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hero_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHero());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof game.proto.HeroChangePush)) {
      return super.equals(obj);
    }
    game.proto.HeroChangePush other = (game.proto.HeroChangePush) obj;

    if (hasHero() != other.hasHero()) return false;
    if (hasHero()) {
      if (!getHero()
          .equals(other.getHero())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHero()) {
      hash = (37 * hash) + HERO_FIELD_NUMBER;
      hash = (53 * hash) + getHero().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static game.proto.HeroChangePush parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.HeroChangePush parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.HeroChangePush parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.HeroChangePush parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.HeroChangePush parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.proto.HeroChangePush parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.proto.HeroChangePush parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.HeroChangePush parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.HeroChangePush parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static game.proto.HeroChangePush parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.proto.HeroChangePush parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.proto.HeroChangePush parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(game.proto.HeroChangePush prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 4003 英雄变化
   * </pre>
   *
   * Protobuf type {@code Message.HeroChangePush}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.HeroChangePush)
      game.proto.HeroChangePushOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.proto.MessageOuterClass.internal_static_Message_HeroChangePush_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.proto.MessageOuterClass.internal_static_Message_HeroChangePush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.proto.HeroChangePush.class, game.proto.HeroChangePush.Builder.class);
    }

    // Construct using game.proto.HeroChangePush.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (heroBuilder_ == null) {
        hero_ = null;
      } else {
        hero_ = null;
        heroBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return game.proto.MessageOuterClass.internal_static_Message_HeroChangePush_descriptor;
    }

    @java.lang.Override
    public game.proto.HeroChangePush getDefaultInstanceForType() {
      return game.proto.HeroChangePush.getDefaultInstance();
    }

    @java.lang.Override
    public game.proto.HeroChangePush build() {
      game.proto.HeroChangePush result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public game.proto.HeroChangePush buildPartial() {
      game.proto.HeroChangePush result = new game.proto.HeroChangePush(this);
      if (heroBuilder_ == null) {
        result.hero_ = hero_;
      } else {
        result.hero_ = heroBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof game.proto.HeroChangePush) {
        return mergeFrom((game.proto.HeroChangePush)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(game.proto.HeroChangePush other) {
      if (other == game.proto.HeroChangePush.getDefaultInstance()) return this;
      if (other.hasHero()) {
        mergeHero(other.getHero());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      game.proto.HeroChangePush parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (game.proto.HeroChangePush) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private game.proto.data.PlayerHero hero_;
    private com.google.protobuf.SingleFieldBuilderV3<
        game.proto.data.PlayerHero, game.proto.data.PlayerHero.Builder, game.proto.data.PlayerHeroOrBuilder> heroBuilder_;
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     * @return Whether the hero field is set.
     */
    public boolean hasHero() {
      return heroBuilder_ != null || hero_ != null;
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     * @return The hero.
     */
    public game.proto.data.PlayerHero getHero() {
      if (heroBuilder_ == null) {
        return hero_ == null ? game.proto.data.PlayerHero.getDefaultInstance() : hero_;
      } else {
        return heroBuilder_.getMessage();
      }
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     */
    public Builder setHero(game.proto.data.PlayerHero value) {
      if (heroBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hero_ = value;
        onChanged();
      } else {
        heroBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     */
    public Builder setHero(
        game.proto.data.PlayerHero.Builder builderForValue) {
      if (heroBuilder_ == null) {
        hero_ = builderForValue.build();
        onChanged();
      } else {
        heroBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     */
    public Builder mergeHero(game.proto.data.PlayerHero value) {
      if (heroBuilder_ == null) {
        if (hero_ != null) {
          hero_ =
            game.proto.data.PlayerHero.newBuilder(hero_).mergeFrom(value).buildPartial();
        } else {
          hero_ = value;
        }
        onChanged();
      } else {
        heroBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     */
    public Builder clearHero() {
      if (heroBuilder_ == null) {
        hero_ = null;
        onChanged();
      } else {
        hero_ = null;
        heroBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     */
    public game.proto.data.PlayerHero.Builder getHeroBuilder() {
      
      onChanged();
      return getHeroFieldBuilder().getBuilder();
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     */
    public game.proto.data.PlayerHeroOrBuilder getHeroOrBuilder() {
      if (heroBuilder_ != null) {
        return heroBuilder_.getMessageOrBuilder();
      } else {
        return hero_ == null ?
            game.proto.data.PlayerHero.getDefaultInstance() : hero_;
      }
    }
    /**
     * <code>.Message.PlayerHero hero = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        game.proto.data.PlayerHero, game.proto.data.PlayerHero.Builder, game.proto.data.PlayerHeroOrBuilder> 
        getHeroFieldBuilder() {
      if (heroBuilder_ == null) {
        heroBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            game.proto.data.PlayerHero, game.proto.data.PlayerHero.Builder, game.proto.data.PlayerHeroOrBuilder>(
                getHero(),
                getParentForChildren(),
                isClean());
        hero_ = null;
      }
      return heroBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.HeroChangePush)
  }

  // @@protoc_insertion_point(class_scope:Message.HeroChangePush)
  private static final game.proto.HeroChangePush DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new game.proto.HeroChangePush();
  }

  public static game.proto.HeroChangePush getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeroChangePush>
      PARSER = new com.google.protobuf.AbstractParser<HeroChangePush>() {
    @java.lang.Override
    public HeroChangePush parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeroChangePush(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeroChangePush> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeroChangePush> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public game.proto.HeroChangePush getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

