// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface HomeNewTaskDayPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.HomeNewTaskDayPush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 day = 1;</code>
   * @return The day.
   */
  int getDay();
}
