// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface KickPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.KickPush)
    com.google.protobuf.MessageOrBuilder {
}
