// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Success_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Success_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_CmdReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_CmdReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ValueChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ValueChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_LoginReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_LoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_LoginRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_LoginRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_KickPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_KickPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerCreateNameReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerCreateNameReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeartbeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeartbeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeartbeatRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeartbeatRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FeatureOpenPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FeatureOpenPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskNewPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskNewPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskStatusChangePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskStatusChangePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskNpcReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskNpcReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskNpcRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskNpcRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskNpcRes_RunTaskEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskNpcRes_RunTaskEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskAbandonReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskAbandonReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TaskAbandonRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TaskAbandonRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightStartReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightStartReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightStartPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightStartPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightTestReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightTestReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightTestRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightTestRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightHmStartRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightHmStartRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightHmActionReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightHmActionReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightHmActionRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightHmActionRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FightHmEndPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FightHmEndPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_BattleEndPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_BattleEndPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_EnterSceneReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_EnterSceneReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_EnterFightAreaReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_EnterFightAreaReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ExitFightAreaReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ExitFightAreaReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_BattleEnterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_BattleEnterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeroUpReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeroUpReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeroChangePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeroChangePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeroTalentChangeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeroTalentChangeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeroTalentChangeRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeroTalentChangeRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_NewHeroPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_NewHeroPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationCreateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationCreateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationCreateRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationCreateRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationUpdateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationUpdateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationUpdateRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationUpdateRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationDeleteReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationDeleteReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationSettingReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationSettingReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FormationSettingRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FormationSettingRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ResourceChangePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ResourceChangePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerLevelChangePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerLevelChangePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ExpChangePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ExpChangePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_RecoverPowerReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_RecoverPowerReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_BagInfoChangePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_BagInfoChangePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_BagCleanReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_BagCleanReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ItemDiscardReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ItemDiscardReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ItemBuyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ItemBuyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ItemExchangeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ItemExchangeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ItemSellReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ItemSellReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HeroEquipmentReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HeroEquipmentReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerMoveReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerMoveReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerGoHotelRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerGoHotelRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerChooseHotelReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerChooseHotelReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerChooseHotelRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerChooseHotelRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FishReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FishReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FishHookPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FishHookPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FishPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FishPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FishHookReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FishHookReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FishEnterAreaReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FishEnterAreaReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_FishExitAreaReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_FishExitAreaReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ChatMessageReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ChatMessageReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ChatMessagePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ChatMessagePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TitleChooseReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TitleChooseReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TitleChooseRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TitleChooseRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TitleNewPush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TitleNewPush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_NpcShowChangePush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_NpcShowChangePush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TempleHeroBuyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TempleHeroBuyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_TempleHeroBuyRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_TempleHeroBuyRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_DungeonEnterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_DungeonEnterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_DungeonEnterRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_DungeonEnterRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_DungeonFightReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_DungeonFightReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_DungeonExitReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_DungeonExitReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_DungeonExitRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_DungeonExitRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ExpressStartRqRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ExpressStartRqRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ExpressCompleteReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ExpressCompleteReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ExpressCompleteRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ExpressCompleteRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_ExpressInfoRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_ExpressInfoRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HomeOpenAreaRqRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HomeOpenAreaRqRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HomeChangeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HomeChangeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HomeHarvestReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HomeHarvestReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HomeHarvestRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HomeHarvestRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HomeCleanReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HomeCleanReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_HomeProductReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_HomeProductReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007Message\032\ndata.proto\"S\n\007" +
      "Message\022\017\n\007version\030\001 \001(\005\022\r\n\005msgNo\030\002 \001(\005\022" +
      "\r\n\005error\030\003 \001(\005\022\013\n\003seq\030\004 \001(\005\022\014\n\004body\030\n \001(" +
      "\014\"\007\n\005Empty\"\t\n\007Success\"\030\n\006CmdReq\022\016\n\006param" +
      "s\030\001 \001(\t\"%\n\013ValueChange\022\n\n\002v1\030\001 \001(\005\022\n\n\002v2" +
      "\030\002 \001(\005\"*\n\010LoginReq\022\020\n\010playerId\030\001 \001(\003\022\014\n\004" +
      "code\030\002 \001(\t\"<\n\010LoginRes\022!\n\004data\030\001 \001(\0132\023.M" +
      "essage.PlayerData\022\r\n\005first\030\003 \001(\010\"\n\n\010Kick" +
      "Push\"#\n\023PlayerCreateNameReq\022\014\n\004name\030\001 \001(" +
      "\t\"\034\n\014HeartbeatReq\022\014\n\004time\030\001 \001(\003\"\034\n\014Heart" +
      "beatRes\022\014\n\004time\030\001 \001(\003\"\035\n\017FeatureOpenPush" +
      "\022\n\n\002id\030\001 \001(\005\"\031\n\007TaskReq\022\016\n\006taskId\030\001 \001(\005\"" +
      "\035\n\013TaskNewPush\022\016\n\006taskId\030\001 \003(\005\"\231\001\n\024TaskS" +
      "tatusChangePush\022\r\n\005npcId\030\n \001(\005\022\016\n\006taskId" +
      "\030\024 \001(\005\022\016\n\006status\030# \001(\005\022\020\n\010targetId\0302 \001(\005" +
      "\022\r\n\005count\030( \001(\005\022\016\n\006accept\030< \001(\010\022!\n\007runTa" +
      "sk\030F \001(\0132\020.Message.RunTask\"\033\n\nTaskNpcReq" +
      "\022\r\n\005npcId\030\001 \001(\005\"\250\001\n\nTaskNpcRes\022\r\n\005npcId\030" +
      "\001 \001(\005\022\026\n\016acceptableTask\030\002 \003(\005\0221\n\007runTask" +
      "\030\003 \003(\0132 .Message.TaskNpcRes.RunTaskEntry" +
      "\032@\n\014RunTaskEntry\022\013\n\003key\030\001 \001(\005\022\037\n\005value\030\002" +
      " \001(\0132\020.Message.RunTask:\0028\001\" \n\016TaskAbando" +
      "nReq\022\016\n\006taskId\030\001 \001(\005\" \n\016TaskAbandonRes\022\016" +
      "\n\006taskId\030\001 \001(\005\"3\n\rFightStartReq\022\"\n\003pos\030\001" +
      " \003(\0132\025.Message.FightHeroPos\"G\n\016FightStar" +
      "tPush\022%\n\004info\030\001 \003(\0132\027.Message.FightEnemy" +
      "Info\022\016\n\006manual\030\002 \001(\010\"\260\001\n\013FightRecord\022#\n\005" +
      "round\030\001 \003(\0132\024.Message.RoundRecord\022&\n\005sid" +
      "eA\030\002 \003(\0132\027.Message.HeroDataRecord\022&\n\005sid" +
      "eB\030\003 \003(\0132\027.Message.HeroDataRecord\022\013\n\003win" +
      "\030\004 \001(\010\022\037\n\006reward\030\005 \003(\0132\017.Message.Reward\"" +
      "T\n\014FightTestReq\022 \n\001a\030\001 \003(\0132\025.Message.Fig" +
      "htHeroPos\022\"\n\001b\030\002 \003(\0132\027.Message.FightEnem" +
      "yInfo\"A\n\014FightTestRes\022\013\n\003win\030\001 \001(\010\022$\n\006re" +
      "cord\030\004 \001(\0132\024.Message.FightRecord\"a\n\017Figh" +
      "tHmStartRes\022&\n\005sideA\030\002 \003(\0132\027.Message.Her" +
      "oDataRecord\022&\n\005sideB\030\003 \003(\0132\027.Message.Her" +
      "oDataRecord\"8\n\020FightHmActionReq\022$\n\003pos\030\001" +
      " \003(\0132\027.Message.FightHmHeroPos\"7\n\020FightHm" +
      "ActionRes\022#\n\005round\030\001 \001(\0132\024.Message.Round" +
      "Record\">\n\016FightHmEndPush\022\013\n\003win\030\004 \001(\010\022\037\n" +
      "\006reward\030\005 \003(\0132\017.Message.Reward\".\n\rBattle" +
      "EndPush\022\013\n\003win\030\001 \001(\010\022\020\n\010battleId\030\002 \001(\005\"1" +
      "\n\rEnterSceneReq\022 \n\004data\030\001 \001(\0132\022.Message." +
      "SceneData\"\037\n\021EnterFightAreaReq\022\n\n\002id\030\001 \001" +
      "(\005\"\036\n\020ExitFightAreaReq\022\n\n\002id\030\001 \001(\005\"\034\n\016Ba" +
      "ttleEnterReq\022\n\n\002id\030\001 \001(\005\"+\n\tHeroUpReq\022\016\n" +
      "\006heroId\030\001 \001(\005\022\016\n\006stepId\030\003 \001(\005\"3\n\016HeroCha" +
      "ngePush\022!\n\004hero\030\001 \001(\0132\023.Message.PlayerHe" +
      "ro\"5\n\023HeroTalentChangeReq\022\016\n\006heroId\030\001 \001(" +
      "\005\022\016\n\006talent\030\002 \001(\005\"5\n\023HeroTalentChangeRes" +
      "\022\016\n\006heroId\030\001 \001(\005\022\016\n\006talent\030\002 \001(\005\"0\n\013NewH" +
      "eroPush\022!\n\004hero\030\001 \001(\0132\023.Message.PlayerHe" +
      "ro\"\024\n\022FormationCreateReq\")\n\022FormationCre" +
      "ateRes\022\023\n\013formationId\030\001 \001(\005\"M\n\022Formation" +
      "UpdateReq\022\023\n\013formationId\030\001 \001(\005\022\"\n\003pos\030\002 " +
      "\001(\0132\025.Message.FormationPos\"T\n\022FormationU" +
      "pdateRes\022\023\n\013formationId\030\001 \001(\005\022)\n\004data\030\002 " +
      "\003(\0132\033.Message.FormationPosUpdate\"#\n\022Form" +
      "ationDeleteReq\022\r\n\005index\030\001 \001(\005\"n\n\023Formati" +
      "onSettingReq\022\r\n\005index\030\001 \001(\005\022\014\n\004name\030\002 \001(" +
      "\t\022\035\n\025defaultFormationIndex\030\003 \001(\005\022\033\n\023aren" +
      "aFormationIndex\030\004 \001(\005\"n\n\023FormationSettin" +
      "gRes\022\r\n\005index\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\035\n\025def" +
      "aultFormationIndex\030\003 \001(\005\022\033\n\023arenaFormati" +
      "onIndex\030\004 \001(\005\"Y\n\022ResourceChangePush\022\022\n\nr" +
      "esourceId\030\001 \001(\005\022\016\n\006heroId\030\002 \001(\005\022\r\n\005count" +
      "\030\003 \001(\005\022\020\n\010curCount\030\004 \001(\005\"&\n\025PlayerLevelC" +
      "hangePush\022\r\n\005value\030\001 \001(\005\"?\n\rExpChangePus" +
      "h\022\016\n\006heroId\030\001 \001(\005\022\016\n\006addExp\030\002 \001(\005\022\016\n\006cur" +
      "Exp\030\003 \001(\005\":\n\017RecoverPowerReq\022\014\n\004type\030\001 \001" +
      "(\005\022\013\n\003gem\030\002 \001(\005\022\014\n\004gold\030\003 \001(\005\"b\n\021BagInfo" +
      "ChangePush\022\r\n\005clean\030\t \001(\010\022\014\n\004type\030\n \001(\005\022" +
      "\020\n\010capacity\030\024 \001(\005\022\036\n\004slot\030\036 \003(\0132\020.Messag" +
      "e.BagSlot\"\033\n\013BagCleanReq\022\014\n\004type\030\001 \001(\005\"M" +
      "\n\016ItemDiscardReq\022\016\n\006itemId\030\001 \001(\005\022\r\n\005coun" +
      "t\030\002 \001(\005\022\016\n\006slotId\030\003 \001(\005\022\014\n\004type\030\004 \001(\005\";\n" +
      "\nItemBuyReq\022\016\n\006itemId\030\001 \001(\005\022\r\n\005count\030\002 \001" +
      "(\005\022\016\n\006shopId\030\003 \001(\005\">\n\017ItemExchangeReq\022\014\n" +
      "\004type\030\001 \001(\005\022\016\n\006slotId\030\002 \001(\005\022\r\n\005count\030\003 \001" +
      "(\005\",\n\013ItemSellReq\022\016\n\006slotId\030\001 \001(\005\022\r\n\005cou" +
      "nt\030\002 \001(\005\"2\n\020HeroEquipmentReq\022\016\n\006slotId\030\001" +
      " \001(\005\022\016\n\006heroId\030\002 \001(\005\"%\n\rPlayerMoveReq\022\t\n" +
      "\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\" \n\020PlayerGoHotelRes\022" +
      "\014\n\004time\030\001 \001(\003\"\"\n\024PlayerChooseHotelReq\022\n\n" +
      "\002id\030\001 \001(\005\"\"\n\024PlayerChooseHotelRes\022\n\n\002id\030" +
      "\001 \001(\005\"\t\n\007FishReq\"\016\n\014FishHookPush\"<\n\010Fish" +
      "Push\022\017\n\007success\030\001 \001(\010\022\037\n\006reward\030\002 \003(\0132\017." +
      "Message.Reward\"\r\n\013FishHookReq\"\036\n\020FishEnt" +
      "erAreaReq\022\n\n\002id\030\001 \001(\005\"\035\n\017FishExitAreaReq" +
      "\022\n\n\002id\030\001 \001(\005\"X\n\016ChatMessageReq\022%\n\007channe" +
      "l\030\001 \001(\0162\024.Message.ChatChannel\022\016\n\006toUser\030" +
      "\002 \001(\003\022\017\n\007content\030\n \001(\t\"\203\001\n\017ChatMessagePu" +
      "sh\022%\n\007channel\030\001 \001(\0162\024.Message.ChatChanne" +
      "l\022\020\n\010fromUser\030\002 \001(\003\022\014\n\004time\030\003 \001(\003\022\n\n\002id\030" +
      "\004 \001(\003\022\017\n\007content\030\n \001(\t\022\014\n\004name\030\013 \001(\t\"\034\n\016" +
      "TitleChooseReq\022\n\n\002id\030\001 \001(\005\"\034\n\016TitleChoos" +
      "eRes\022\n\n\002id\030\001 \001(\005\"\032\n\014TitleNewPush\022\n\n\002id\030\001" +
      " \001(\005\"2\n\021NpcShowChangePush\022\016\n\006showNo\030\001 \001(" +
      "\005\022\r\n\005npcId\030\002 \001(\005\",\n\020TempleHeroBuyReq\022\n\n\002" +
      "id\030\001 \001(\005\022\014\n\004type\030\002 \001(\005\"\036\n\020TempleHeroBuyR" +
      "es\022\n\n\002id\030\001 \001(\005\"\035\n\017DungeonEnterReq\022\n\n\002id\030" +
      "\001 \001(\005\"\021\n\017DungeonEnterRes\"#\n\017DungeonFight" +
      "Req\022\020\n\010targetId\030\001 \001(\005\"\020\n\016DungeonExitReq\"" +
      "\020\n\016DungeonExitRes\"\036\n\020ExpressStartRqRs\022\n\n" +
      "\002id\030\001 \001(\005\"\024\n\022ExpressCompleteReq\" \n\022Expre" +
      "ssCompleteRes\022\n\n\002id\030\001 \001(\005\".\n\016ExpressInfo" +
      "Res\022\016\n\006update\030\001 \001(\010\022\014\n\004info\030\002 \003(\005\"\036\n\020Hom" +
      "eOpenAreaRqRs\022\n\n\002id\030\001 \001(\005\"3\n\rHomeChangeR" +
      "eq\022\"\n\004data\030\005 \003(\0132\024.Message.HomePosData\"\035" +
      "\n\016HomeHarvestReq\022\013\n\003pos\030\003 \003(\005\">\n\016HomeHar" +
      "vestRes\022\013\n\003pos\030\003 \001(\005\022\037\n\004rect\030\004 \003(\0132\021.Mes" +
      "sage.HomeRect\"\033\n\014HomeCleanReq\022\013\n\003pos\030\003 \003" +
      "(\005\"1\n\016HomeProductReq\022\021\n\tproductId\030\001 \001(\005\022" +
      "\014\n\004type\030\002 \001(\005*R\n\013ChatChannel\022\n\n\006C_NONE\020\000" +
      "\022\t\n\005WORLD\020\001\022\t\n\005GROUP\020\002\022\013\n\007PRIVACY\020\003\022\n\n\006S" +
      "YSTEM\020\004\022\010\n\004NEAR\020\005B\020\n\ngame.protoH\001P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          game.proto.data.Data.getDescriptor(),
        });
    internal_static_Message_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Message_descriptor,
        new java.lang.String[] { "Version", "MsgNo", "Error", "Seq", "Body", });
    internal_static_Message_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Message_Success_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Message_Success_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Success_descriptor,
        new java.lang.String[] { });
    internal_static_Message_CmdReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Message_CmdReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_CmdReq_descriptor,
        new java.lang.String[] { "Params", });
    internal_static_Message_ValueChange_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Message_ValueChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ValueChange_descriptor,
        new java.lang.String[] { "V1", "V2", });
    internal_static_Message_LoginReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Message_LoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_LoginReq_descriptor,
        new java.lang.String[] { "PlayerId", "Code", });
    internal_static_Message_LoginRes_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Message_LoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_LoginRes_descriptor,
        new java.lang.String[] { "Data", "First", });
    internal_static_Message_KickPush_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Message_KickPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_KickPush_descriptor,
        new java.lang.String[] { });
    internal_static_Message_PlayerCreateNameReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Message_PlayerCreateNameReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerCreateNameReq_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_Message_HeartbeatReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Message_HeartbeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeartbeatReq_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_Message_HeartbeatRes_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Message_HeartbeatRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeartbeatRes_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_Message_FeatureOpenPush_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Message_FeatureOpenPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FeatureOpenPush_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_TaskReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Message_TaskReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskReq_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_Message_TaskNewPush_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Message_TaskNewPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskNewPush_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_Message_TaskStatusChangePush_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Message_TaskStatusChangePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskStatusChangePush_descriptor,
        new java.lang.String[] { "NpcId", "TaskId", "Status", "TargetId", "Count", "Accept", "RunTask", });
    internal_static_Message_TaskNpcReq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Message_TaskNpcReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskNpcReq_descriptor,
        new java.lang.String[] { "NpcId", });
    internal_static_Message_TaskNpcRes_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Message_TaskNpcRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskNpcRes_descriptor,
        new java.lang.String[] { "NpcId", "AcceptableTask", "RunTask", });
    internal_static_Message_TaskNpcRes_RunTaskEntry_descriptor =
      internal_static_Message_TaskNpcRes_descriptor.getNestedTypes().get(0);
    internal_static_Message_TaskNpcRes_RunTaskEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskNpcRes_RunTaskEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Message_TaskAbandonReq_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Message_TaskAbandonReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskAbandonReq_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_Message_TaskAbandonRes_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Message_TaskAbandonRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TaskAbandonRes_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_Message_FightStartReq_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Message_FightStartReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightStartReq_descriptor,
        new java.lang.String[] { "Pos", });
    internal_static_Message_FightStartPush_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Message_FightStartPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightStartPush_descriptor,
        new java.lang.String[] { "Info", "Manual", });
    internal_static_Message_FightRecord_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Message_FightRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightRecord_descriptor,
        new java.lang.String[] { "Round", "SideA", "SideB", "Win", "Reward", });
    internal_static_Message_FightTestReq_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Message_FightTestReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightTestReq_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_Message_FightTestRes_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Message_FightTestRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightTestRes_descriptor,
        new java.lang.String[] { "Win", "Record", });
    internal_static_Message_FightHmStartRes_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Message_FightHmStartRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightHmStartRes_descriptor,
        new java.lang.String[] { "SideA", "SideB", });
    internal_static_Message_FightHmActionReq_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Message_FightHmActionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightHmActionReq_descriptor,
        new java.lang.String[] { "Pos", });
    internal_static_Message_FightHmActionRes_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_Message_FightHmActionRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightHmActionRes_descriptor,
        new java.lang.String[] { "Round", });
    internal_static_Message_FightHmEndPush_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Message_FightHmEndPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FightHmEndPush_descriptor,
        new java.lang.String[] { "Win", "Reward", });
    internal_static_Message_BattleEndPush_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_Message_BattleEndPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_BattleEndPush_descriptor,
        new java.lang.String[] { "Win", "BattleId", });
    internal_static_Message_EnterSceneReq_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_Message_EnterSceneReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_EnterSceneReq_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_Message_EnterFightAreaReq_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_Message_EnterFightAreaReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_EnterFightAreaReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_ExitFightAreaReq_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_Message_ExitFightAreaReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ExitFightAreaReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_BattleEnterReq_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_Message_BattleEnterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_BattleEnterReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_HeroUpReq_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_Message_HeroUpReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeroUpReq_descriptor,
        new java.lang.String[] { "HeroId", "StepId", });
    internal_static_Message_HeroChangePush_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_Message_HeroChangePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeroChangePush_descriptor,
        new java.lang.String[] { "Hero", });
    internal_static_Message_HeroTalentChangeReq_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_Message_HeroTalentChangeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeroTalentChangeReq_descriptor,
        new java.lang.String[] { "HeroId", "Talent", });
    internal_static_Message_HeroTalentChangeRes_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_Message_HeroTalentChangeRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeroTalentChangeRes_descriptor,
        new java.lang.String[] { "HeroId", "Talent", });
    internal_static_Message_NewHeroPush_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_Message_NewHeroPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_NewHeroPush_descriptor,
        new java.lang.String[] { "Hero", });
    internal_static_Message_FormationCreateReq_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_Message_FormationCreateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationCreateReq_descriptor,
        new java.lang.String[] { });
    internal_static_Message_FormationCreateRes_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_Message_FormationCreateRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationCreateRes_descriptor,
        new java.lang.String[] { "FormationId", });
    internal_static_Message_FormationUpdateReq_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_Message_FormationUpdateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationUpdateReq_descriptor,
        new java.lang.String[] { "FormationId", "Pos", });
    internal_static_Message_FormationUpdateRes_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_Message_FormationUpdateRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationUpdateRes_descriptor,
        new java.lang.String[] { "FormationId", "Data", });
    internal_static_Message_FormationDeleteReq_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_Message_FormationDeleteReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationDeleteReq_descriptor,
        new java.lang.String[] { "Index", });
    internal_static_Message_FormationSettingReq_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_Message_FormationSettingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationSettingReq_descriptor,
        new java.lang.String[] { "Index", "Name", "DefaultFormationIndex", "ArenaFormationIndex", });
    internal_static_Message_FormationSettingRes_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_Message_FormationSettingRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FormationSettingRes_descriptor,
        new java.lang.String[] { "Index", "Name", "DefaultFormationIndex", "ArenaFormationIndex", });
    internal_static_Message_ResourceChangePush_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_Message_ResourceChangePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ResourceChangePush_descriptor,
        new java.lang.String[] { "ResourceId", "HeroId", "Count", "CurCount", });
    internal_static_Message_PlayerLevelChangePush_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_Message_PlayerLevelChangePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerLevelChangePush_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_Message_ExpChangePush_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_Message_ExpChangePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ExpChangePush_descriptor,
        new java.lang.String[] { "HeroId", "AddExp", "CurExp", });
    internal_static_Message_RecoverPowerReq_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_Message_RecoverPowerReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_RecoverPowerReq_descriptor,
        new java.lang.String[] { "Type", "Gem", "Gold", });
    internal_static_Message_BagInfoChangePush_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_Message_BagInfoChangePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_BagInfoChangePush_descriptor,
        new java.lang.String[] { "Clean", "Type", "Capacity", "Slot", });
    internal_static_Message_BagCleanReq_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_Message_BagCleanReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_BagCleanReq_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_Message_ItemDiscardReq_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_Message_ItemDiscardReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ItemDiscardReq_descriptor,
        new java.lang.String[] { "ItemId", "Count", "SlotId", "Type", });
    internal_static_Message_ItemBuyReq_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_Message_ItemBuyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ItemBuyReq_descriptor,
        new java.lang.String[] { "ItemId", "Count", "ShopId", });
    internal_static_Message_ItemExchangeReq_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_Message_ItemExchangeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ItemExchangeReq_descriptor,
        new java.lang.String[] { "Type", "SlotId", "Count", });
    internal_static_Message_ItemSellReq_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_Message_ItemSellReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ItemSellReq_descriptor,
        new java.lang.String[] { "SlotId", "Count", });
    internal_static_Message_HeroEquipmentReq_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_Message_HeroEquipmentReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HeroEquipmentReq_descriptor,
        new java.lang.String[] { "SlotId", "HeroId", });
    internal_static_Message_PlayerMoveReq_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_Message_PlayerMoveReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerMoveReq_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_Message_PlayerGoHotelRes_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_Message_PlayerGoHotelRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerGoHotelRes_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_Message_PlayerChooseHotelReq_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_Message_PlayerChooseHotelReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerChooseHotelReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_PlayerChooseHotelRes_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_Message_PlayerChooseHotelRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerChooseHotelRes_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_FishReq_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_Message_FishReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FishReq_descriptor,
        new java.lang.String[] { });
    internal_static_Message_FishHookPush_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_Message_FishHookPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FishHookPush_descriptor,
        new java.lang.String[] { });
    internal_static_Message_FishPush_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_Message_FishPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FishPush_descriptor,
        new java.lang.String[] { "Success", "Reward", });
    internal_static_Message_FishHookReq_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_Message_FishHookReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FishHookReq_descriptor,
        new java.lang.String[] { });
    internal_static_Message_FishEnterAreaReq_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_Message_FishEnterAreaReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FishEnterAreaReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_FishExitAreaReq_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_Message_FishExitAreaReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_FishExitAreaReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_ChatMessageReq_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_Message_ChatMessageReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ChatMessageReq_descriptor,
        new java.lang.String[] { "Channel", "ToUser", "Content", });
    internal_static_Message_ChatMessagePush_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_Message_ChatMessagePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ChatMessagePush_descriptor,
        new java.lang.String[] { "Channel", "FromUser", "Time", "Id", "Content", "Name", });
    internal_static_Message_TitleChooseReq_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_Message_TitleChooseReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TitleChooseReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_TitleChooseRes_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_Message_TitleChooseRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TitleChooseRes_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_TitleNewPush_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_Message_TitleNewPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TitleNewPush_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_NpcShowChangePush_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_Message_NpcShowChangePush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_NpcShowChangePush_descriptor,
        new java.lang.String[] { "ShowNo", "NpcId", });
    internal_static_Message_TempleHeroBuyReq_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_Message_TempleHeroBuyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TempleHeroBuyReq_descriptor,
        new java.lang.String[] { "Id", "Type", });
    internal_static_Message_TempleHeroBuyRes_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_Message_TempleHeroBuyRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_TempleHeroBuyRes_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_DungeonEnterReq_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_Message_DungeonEnterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_DungeonEnterReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_DungeonEnterRes_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_Message_DungeonEnterRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_DungeonEnterRes_descriptor,
        new java.lang.String[] { });
    internal_static_Message_DungeonFightReq_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_Message_DungeonFightReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_DungeonFightReq_descriptor,
        new java.lang.String[] { "TargetId", });
    internal_static_Message_DungeonExitReq_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_Message_DungeonExitReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_DungeonExitReq_descriptor,
        new java.lang.String[] { });
    internal_static_Message_DungeonExitRes_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_Message_DungeonExitRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_DungeonExitRes_descriptor,
        new java.lang.String[] { });
    internal_static_Message_ExpressStartRqRs_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_Message_ExpressStartRqRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ExpressStartRqRs_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_ExpressCompleteReq_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_Message_ExpressCompleteReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ExpressCompleteReq_descriptor,
        new java.lang.String[] { });
    internal_static_Message_ExpressCompleteRes_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_Message_ExpressCompleteRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ExpressCompleteRes_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_ExpressInfoRes_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_Message_ExpressInfoRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_ExpressInfoRes_descriptor,
        new java.lang.String[] { "Update", "Info", });
    internal_static_Message_HomeOpenAreaRqRs_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_Message_HomeOpenAreaRqRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HomeOpenAreaRqRs_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Message_HomeChangeReq_descriptor =
      getDescriptor().getMessageTypes().get(84);
    internal_static_Message_HomeChangeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HomeChangeReq_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_Message_HomeHarvestReq_descriptor =
      getDescriptor().getMessageTypes().get(85);
    internal_static_Message_HomeHarvestReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HomeHarvestReq_descriptor,
        new java.lang.String[] { "Pos", });
    internal_static_Message_HomeHarvestRes_descriptor =
      getDescriptor().getMessageTypes().get(86);
    internal_static_Message_HomeHarvestRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HomeHarvestRes_descriptor,
        new java.lang.String[] { "Pos", "Rect", });
    internal_static_Message_HomeCleanReq_descriptor =
      getDescriptor().getMessageTypes().get(87);
    internal_static_Message_HomeCleanReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HomeCleanReq_descriptor,
        new java.lang.String[] { "Pos", });
    internal_static_Message_HomeProductReq_descriptor =
      getDescriptor().getMessageTypes().get(88);
    internal_static_Message_HomeProductReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_HomeProductReq_descriptor,
        new java.lang.String[] { "ProductId", "Type", });
    game.proto.data.Data.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
