// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface NpcShowChangePushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.NpcShowChangePush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 showNo = 1;</code>
   * @return The showNo.
   */
  int getShowNo();

  /**
   * <code>int32 npcId = 2;</code>
   * @return The npcId.
   */
  int getNpcId();
}
