// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface PlayerChooseHotelResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.PlayerChooseHotelRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
