// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface RecoverPowerReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.RecoverPowerReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1:全部，2:单个
   * </pre>
   *
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>int32 gem = 2;</code>
   * @return The gem.
   */
  int getGem();

  /**
   * <code>int32 gold = 3;</code>
   * @return The gold.
   */
  int getGold();
}
