// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface RunTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.RunTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 taskId = 1;</code>
   * @return The taskId.
   */
  int getTaskId();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();
}
