// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package game.proto;

public interface TaskNpcReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.TaskNpcReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 npcId = 1;</code>
   * @return The npcId.
   */
  int getNpcId();
}
