// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: back.proto

package game.proto.back;

public final class Back {
  private Back() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_PlayerBackData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_PlayerBackData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_SaveData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_SaveData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nback.proto\022\007Message\032\ndata.proto\"w\n\016Pla" +
      "yerBackData\022\021\n\tfightTime\030\001 \001(\003\022\021\n\tfightA" +
      "rea\030\002 \003(\005\022\030\n\020powerRecoverTime\030\003 \001(\003\022\021\n\tl" +
      "oginTime\030\005 \001(\003\022\022\n\nupdateTime\030\006 \001(\003\"V\n\010Sa" +
      "veData\022)\n\010backData\030\001 \001(\0132\027.Message.Playe" +
      "rBackData\022\037\n\002pd\030\002 \001(\0132\023.Message.PlayerDa" +
      "taB\025\n\017game.proto.backH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          game.proto.data.Data.getDescriptor(),
        });
    internal_static_Message_PlayerBackData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_PlayerBackData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_PlayerBackData_descriptor,
        new java.lang.String[] { "FightTime", "FightArea", "PowerRecoverTime", "LoginTime", "UpdateTime", });
    internal_static_Message_SaveData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_SaveData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_SaveData_descriptor,
        new java.lang.String[] { "BackData", "Pd", });
    game.proto.data.Data.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
