// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: back.proto

package game.proto.back;

public interface LadderResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.LadderResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 单挑
   * </pre>
   *
   * <code>int32 type = 3;</code>
   * @return The type.
   */
  int getType();
}
