// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: no.proto

package game.proto.no;

public final class NoOuterClass {
  private NoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010no.proto\022\002No*T\n\002No\022\010\n\004NONE\020\000\022\014\n\007FishRe" +
      "q\020\301>\022\020\n\013FishHookReq\020\302>\022\022\n\rFightStartReq\020" +
      "\321\017\022\020\n\013FightEndReq\020\324\017B\023\n\rgame.proto.noH\001P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
